import assert from "node:assert/strict";
import { appendFile, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";

import {
  classifyChannelTab,
  channelCatalogPage,
  discoverChannelCatalog,
  findBrowseContinuation,
  parseChannelCatalogItems,
  parseChannelTabEndpoints,
} from "./channel-catalog.js";
import { batchPackFor } from "./batch.js";
import { exportChannelAnalysis } from "./channel-export.js";
import { DiskCache } from "./cache.js";
import { ExtractError } from "./errors.js";
import type { Engine } from "./transcript.js";
import type { Transcript, VideoInfo } from "./types.js";

const VIDEO_1 = "aaaaaaaaaaa";
const VIDEO_2 = "bbbbbbbbbbb";
const SHORT_1 = "ccccccccccc";
const CHANNEL_ID = "UC1234567890123456789012";

function richVideo(id: string, title: string) {
  return {
    richItemRenderer: {
      content: {
        videoRenderer: {
          videoId: id,
          title: { runs: [{ text: title }] },
          lengthText: { simpleText: "2:00" },
        },
      },
    },
  };
}

function shortLockup(id: string, title: string) {
  return {
    richItemRenderer: {
      content: {
        shortsLockupViewModel: {
          onTap: { innertubeCommand: { reelWatchEndpoint: { videoId: id } } },
          overlayMetadata: { primaryText: { content: title } },
        },
      },
    },
  };
}

function continuation(token: string) {
  return {
    continuationItemRenderer: {
      continuationEndpoint: { continuationCommand: { token } },
    },
  };
}

function selectedPage(contents: unknown[]) {
  return {
    contents: {
      twoColumnBrowseResultsRenderer: {
        tabs: [
          {
            tabRenderer: {
              selected: true,
              content: { richGridRenderer: { contents } },
            },
          },
        ],
      },
    },
  };
}

function channelHome() {
  return {
    metadata: {
      channelMetadataRenderer: {
        title: "Fixture Creator",
        description: "Fixture channel",
      },
    },
    contents: {
      twoColumnBrowseResultsRenderer: {
        tabs: [
          {
            tabRenderer: {
              title: "Videos",
              endpoint: { browseEndpoint: { browseId: CHANNEL_ID, params: "VIDEOS" } },
            },
          },
          {
            tabRenderer: {
              title: "Shorts",
              endpoint: { browseEndpoint: { browseId: CHANNEL_ID, params: "SHORTS" } },
            },
          },
        ],
      },
    },
  };
}

function transcriptFor(id: string): Transcript {
  return {
    videoId: id,
    languageCode: "en",
    languageName: "English",
    isAutoGenerated: false,
    merged: false,
    rawSegmentCount: 1,
    segmentCount: 1,
    durationSeconds: 2,
    segments: [
      {
        text: `Transcript ${id}`,
        start: 0,
        duration: 2,
        end: 2,
        timestamp: "0:00",
        timestampEnd: "0:02",
      },
    ],
    lines: [`[0:00] Transcript ${id}`],
    text: `Transcript ${id}`,
  };
}

function infoFor(id: string): VideoInfo {
  return {
    id,
    url: `https://www.youtube.com/watch?v=${id}`,
    title: `Video ${id}`,
    description: "",
    channelId: CHANNEL_ID,
    channelName: "Fixture Creator",
    durationSeconds: 2,
    isLive: false,
    isFamilySafe: true,
    thumbnails: [],
  };
}

async function fixtureEngine(
  dir: string,
  transcriptHook?: (id: string) => Transcript,
  browseHook?: (body: Record<string, unknown>) => unknown,
): Promise<Engine> {
  const cache = new DiskCache({ dir, limit: 0 });
  const client = {
    cache,
    callJSON: async (_endpoint: string, _profile: unknown, body: Record<string, unknown>) => {
      const hooked = browseHook?.(body);
      if (hooked !== undefined) return hooked;
      if (body["browseId"] && !body["params"]) return channelHome();
      if (body["params"] === "VIDEOS") {
        return selectedPage([richVideo(VIDEO_1, "Long one"), continuation("VIDEOS_NEXT")]);
      }
      if (body["continuation"] === "VIDEOS_NEXT") {
        return { onResponseReceivedActions: [{ appendContinuationItemsAction: {
          continuationItems: [richVideo(VIDEO_2, "Also appears in Shorts")],
        } }] };
      }
      if (body["params"] === "SHORTS") {
        return selectedPage([
          shortLockup(VIDEO_2, "Duplicate Short"),
          shortLockup(SHORT_1, "Short one"),
        ]);
      }
      throw new Error("Unexpected fixture browse body: " + JSON.stringify(body));
    },
  };
  return {
    client,
    info: async (id: string) => infoFor(id),
    chapters: async (id: string) => ({
      videoId: id,
      title: `Video ${id}`,
      chapters: [{ title: "Intro", startSeconds: 0, timestamp: "0:00" }],
      count: 1,
      hasChapters: true,
      source: "description",
    }),
    transcript: async (id: string) => transcriptHook?.(id) ?? transcriptFor(id),
  } as unknown as Engine;
}

describe("creator channel catalog", () => {
  it("recognizes Videos and Shorts tabs and continuation tokens", () => {
    assert.equal(classifyChannelTab("Videos"), "videos");
    assert.equal(classifyChannelTab("Shorts"), "shorts");
    assert.deepEqual(parseChannelTabEndpoints(channelHome()).map((t) => t.kind), ["videos", "shorts"]);
    assert.equal(findBrowseContinuation(selectedPage([continuation("NEXT")])), "NEXT");
  });

  it("parses leaf and wrapped catalog renderers", () => {
    const entries = parseChannelCatalogItems({
      contents: [richVideo(VIDEO_1, "Long one"), shortLockup(SHORT_1, "Short one")],
    });
    assert.deepEqual(entries.map((e) => e.id), [VIDEO_1, SHORT_1]);
  });

  it("exhausts both tabs, resumes continuations, and lets Shorts provenance win", async () => {
    const dir = await mkdtemp(join(tmpdir(), "ytube-catalog-test-"));
    try {
      const engine = await fixtureEngine(dir);
      const result = await discoverChannelCatalog(
        engine,
        CHANNEL_ID,
        { contentType: "all", ensure: 0 },
      );
      assert.equal(result.complete, true);
      assert.equal(result.count, 3);
      assert.equal(result.videoCount, 1);
      assert.equal(result.shortCount, 2);
      assert.deepEqual(
        result.items.map((item) => [item.id, item.contentType]),
        [[VIDEO_1, "video"], [VIDEO_2, "short"], [SHORT_1, "short"]],
      );

      const cached = await discoverChannelCatalog(
        engine,
        CHANNEL_ID,
        { contentType: "shorts", ensure: 0 },
      );
      assert.deepEqual(cached.items.map((item) => item.id), [VIDEO_2, SHORT_1]);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("returns full metadata, transcript, chapters, and chunks in analysis pages", async () => {
    const dir = await mkdtemp(join(tmpdir(), "ytube-channel-batch-test-"));
    try {
      const engine = await fixtureEngine(dir);
      const page = await batchPackFor(engine, CHANNEL_ID, {
        contentType: "videos",
        detail: "analysis",
        limit: 1,
      });
      assert.equal(page.videos.length, 1);
      assert.equal(page.videos[0]?.contentType, "video");
      assert.equal(page.videos[0]?.video?.id, VIDEO_1);
      assert.equal(page.videos[0]?.transcript?.segmentCount, 1);
      assert.equal(page.videos[0]?.chapters?.length, 1);
      assert.equal(page.videos[0]?.chunks?.length, 1);
      assert.equal(page.catalogComplete, true);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("uses the documented 50-item default instead of collapsing an omitted limit to one", async () => {
    const dir = await mkdtemp(join(tmpdir(), "ytube-channel-page-test-"));
    try {
      const engine = await fixtureEngine(dir);
      const page = await channelCatalogPage(engine, CHANNEL_ID, { contentType: "videos" });
      assert.equal(page.items.length, 2);
      assert.equal(page.complete, true);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("keeps progressive state readable after ordinary cache TTL expiry", async () => {
    const dir = await mkdtemp(join(tmpdir(), "ytube-persistent-cache-test-"));
    try {
      const cache = new DiskCache({ dir, ttlMs: 0, limit: 0 });
      await cache.set("channel-catalog", CHANNEL_ID, { cursor: "NEXT" });
      await new Promise((resolve) => setTimeout(resolve, 2));
      assert.equal(await cache.get("channel-catalog", CHANNEL_ID), undefined);
      assert.deepEqual(
        await cache.getPersistent("channel-catalog", CHANNEL_ID),
        { cursor: "NEXT" },
      );
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});

describe("checkpointed channel export", () => {
  it("writes one analysis/failure record per item and resumes without duplicates", async () => {
    const dir = await mkdtemp(join(tmpdir(), "ytube-export-test-"));
    const prior = process.env["YTUBE_EXPORT_DIR"];
    process.env["YTUBE_EXPORT_DIR"] = join(dir, "exports");
    try {
      const engine = await fixtureEngine(dir, (id) => {
        if (id === VIDEO_2) {
          throw new ExtractError({ code: "CAPTIONS_DISABLED", message: "No captions" });
        }
        return transcriptFor(id);
      });
      const first = await exportChannelAnalysis(engine, CHANNEL_ID, {
        contentType: "all",
        jobId: "fixture-export-job",
      });
      assert.equal(first.status, "completed");
      assert.equal(first.succeeded, 2);
      assert.equal(first.failed, 1);

      const lines = (await readFile(first.dataPath, "utf8")).trim().split("\n");
      assert.equal(lines.length, 3);
      assert.deepEqual(lines.map((line) => JSON.parse(line).type), ["video", "failure", "video"]);

      // Simulate a partial fourth append and a stale checkpoint.
      await appendFile(first.dataPath, "{\"type\":");
      const staleState = JSON.parse(await readFile(first.checkpointPath, "utf8"));
      staleState.status = "paused";
      staleState.cursor = 2;
      staleState.succeeded = 1;
      await writeFile(first.checkpointPath, JSON.stringify(staleState));

      const resumed = await exportChannelAnalysis(engine, CHANNEL_ID, {
        contentType: "all",
        jobId: first.jobId,
      });
      assert.equal(resumed.status, "completed");
      const resumedLines = (await readFile(first.dataPath, "utf8")).trim().split("\n");
      assert.equal(resumedLines.length, 3);
    } finally {
      if (prior === undefined) delete process.env["YTUBE_EXPORT_DIR"];
      else process.env["YTUBE_EXPORT_DIR"] = prior;
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("pauses on a global rate failure and retries the same item", async () => {
    const dir = await mkdtemp(join(tmpdir(), "ytube-export-pause-test-"));
    const prior = process.env["YTUBE_EXPORT_DIR"];
    process.env["YTUBE_EXPORT_DIR"] = join(dir, "exports");
    let blocked = true;
    try {
      const engine = await fixtureEngine(dir, (id) => {
        if (blocked) {
          throw new ExtractError({
            code: "RATE_LIMITED",
            message: "Try later",
            retryable: true,
          });
        }
        return transcriptFor(id);
      });
      const paused = await exportChannelAnalysis(engine, CHANNEL_ID, {
        jobId: "fixture-paused-job",
      });
      assert.equal(paused.status, "paused");
      assert.equal(paused.cursor, 0);
      assert.equal((await readFile(paused.dataPath, "utf8")).length, 0);

      blocked = false;
      const resumed = await exportChannelAnalysis(engine, CHANNEL_ID, {
        jobId: paused.jobId,
      });
      assert.equal(resumed.status, "completed");
      assert.equal(resumed.succeeded, 3);
    } finally {
      if (prior === undefined) delete process.env["YTUBE_EXPORT_DIR"];
      else process.env["YTUBE_EXPORT_DIR"] = prior;
      await rm(dir, { recursive: true, force: true });
    }
  });

  it("checkpoints catalog discovery failures before any video is processed", async () => {
    const dir = await mkdtemp(join(tmpdir(), "ytube-export-catalog-pause-test-"));
    const prior = process.env["YTUBE_EXPORT_DIR"];
    process.env["YTUBE_EXPORT_DIR"] = join(dir, "exports");
    let blocked = true;
    try {
      const engine = await fixtureEngine(
        dir,
        undefined,
        (body) => {
          if (blocked && body["continuation"] === "VIDEOS_NEXT") {
            throw new ExtractError({
              code: "RATE_BUDGET_EXCEEDED",
              message: "Catalog budget spent",
              retryable: true,
            });
          }
          return undefined;
        },
      );
      const paused = await exportChannelAnalysis(engine, CHANNEL_ID, {
        jobId: "fixture-catalog-pause-job",
      });
      assert.equal(paused.status, "paused");
      assert.equal(paused.cursor, 0);
      assert.equal(paused.lastError?.code, "RATE_BUDGET_EXCEEDED");

      blocked = false;
      const resumed = await exportChannelAnalysis(engine, CHANNEL_ID, {
        jobId: paused.jobId,
      });
      assert.equal(resumed.status, "completed");
      assert.equal(resumed.catalogVideos, 3);
      assert.equal(resumed.succeeded, 3);
    } finally {
      if (prior === undefined) delete process.env["YTUBE_EXPORT_DIR"];
      else process.env["YTUBE_EXPORT_DIR"] = prior;
      await rm(dir, { recursive: true, force: true });
    }
  });
});
