/**
 * Per-stage report of the caption resolution ladder, for when a transcript call
 * returns an opaque error. Ported from internal/youtube/diagnose.go.
 */
import {
  browserTranscriptEnabled,
  isBrowserTranscriptAvailable,
} from "./browser-transcript.js";
import { isExtractError } from "./errors.js";
import { parseVideoId } from "./ids.js";
import {
  isTimedtextCoolingDown,
  timedtextCooldownRemainingSec,
} from "./timedtext-gate.js";
import {
  errorText,
  pickCaptionTrack,
  transcriptCacheKey,
  withFormat,
  type Engine,
  type PickCaptionResult,
} from "./transcript.js";
import type {
  CaptionTrack,
  CaptionTrackBrief,
  ClientProbe,
  Transcript,
  TranscriptDiagnosis,
  TranscriptSegment,
} from "./types.js";

export type {
  CaptionTrackBrief,
  ClientProbe,
  SelectedTrackInfo,
  TranscriptDiagnosis,
} from "./types.js";

/** Attempts look like "ANDROID: OK tracks=2" or "WEB: UNPLAYABLE (…)". */
function probeFromAttempt(line: string, withError: boolean): ClientProbe {
  const probe: ClientProbe = { client: "?", status: line, trackCount: 0 };
  const i = line.indexOf(":");
  if (i <= 0) {
    return probe;
  }
  probe.client = line.slice(0, i);
  const rest = line.slice(i + 1).trim();
  const fields = rest.split(/\s+/).filter(Boolean);
  if (fields.length > 0) {
    probe.status = fields[0]!;
  }
  for (const f of fields) {
    if (f.startsWith("tracks=")) {
      const n = Number.parseInt(f.slice("tracks=".length), 10);
      if (Number.isFinite(n)) {
        probe.trackCount = n;
      }
    }
  }
  if (withError && rest.includes(" ") && !rest.startsWith("OK") && !rest.startsWith("UNPLAYABLE")) {
    probe.error = rest;
  }
  return probe;
}

function briefFromTrack(t: CaptionTrack): CaptionTrackBrief {
  const altUrlCount = t.altUrls?.length ?? 0;
  return {
    languageCode: t.languageCode,
    name: t.name,
    isAutoGenerated: t.isAutoGenerated,
    isTranslatable: t.isTranslatable,
    sourceClient: t.sourceClient ? t.sourceClient : undefined,
    altUrlCount: altUrlCount > 0 ? altUrlCount : undefined,
  };
}

function estimateBodyBytes(segs: TranscriptSegment[]): number {
  let n = 0;
  for (const s of segs) {
    n += Buffer.byteLength(s.text, "utf8");
  }
  return n;
}

/**
 * Runs the caption ladder and reports each stage without failing early. Only
 * an unusable input (bad video ID) throws; everything else lands in `error`.
 */
export async function diagnoseTranscript(
  engine: Engine,
  input: string,
  lang?: string,
  signal?: AbortSignal,
): Promise<TranscriptDiagnosis> {
  const id = parseVideoId(input);
  const hl = (process.env.YTUBE_HL ?? "").trim() || "en";
  const gl = (process.env.YTUBE_GL ?? "").trim() || "US";

  const diag: TranscriptDiagnosis = {
    videoId: id,
    ok: false,
    clients: [],
    cacheHit: false,
    staleAvailable: false,
    rateBudgetRemaining: await engine.client.rateBudgetRemaining(),
    poTokenConfigured: (process.env.YTUBE_PO_TOKEN ?? "").trim() !== "",
    hl,
    gl,
    browserConfigured: browserTranscriptEnabled({}),
    browserAvailable: await isBrowserTranscriptAvailable(),
  };

  const opts = { lang };
  const cacheKey = transcriptCacheKey(id, opts);
  const cached = await engine.client.cache.get<Transcript>("transcript", cacheKey);
  if (cached !== undefined) {
    diag.cacheHit = true;
    diag.ok = true;
    diag.segmentCount = cached.segmentCount;
    diag.selected = {
      languageCode: cached.languageCode,
      source: cached.source ?? "",
      translatedFrom: cached.translatedFrom || undefined,
      warnings: cached.warnings && cached.warnings.length > 0 ? cached.warnings : undefined,
    };
    diag.formatUsed = "cache";
    // Still list tracks cheaply when possible, but skip caption body GETs.
    const resolved = await engine.resolveCaptionTracksResult(id, signal);
    if (resolved.error === undefined) {
      diag.attempts = resolved.attempts;
      diag.clients = resolved.attempts.map((line) => probeFromAttempt(line, false));
      diag.tracks = resolved.tracks.map(briefFromTrack);
    }
    return diag;
  }
  // Prefer cache / stale over burning another timedtext GET.
  if ((await engine.client.cache.getStale<Transcript>("transcript", cacheKey)) !== undefined) {
    diag.staleAvailable = true;
  }

  // Skip caption-body probes while timedtext is cooling down after a 429.
  if (isTimedtextCoolingDown()) {
    diag.error = `RATE_LIMITED: timedtext cooldown (~${timedtextCooldownRemainingSec()}s); skipped body probe`;
    const resolved = await engine.resolveCaptionTracksResult(id, signal);
    diag.attempts = resolved.attempts;
    diag.clients = resolved.attempts.map((line) => probeFromAttempt(line, true));
    if (resolved.error === undefined) {
      diag.tracks = resolved.tracks.map(briefFromTrack);
    }
    if (diag.staleAvailable || diag.cacheHit) {
      diag.ok = true;
      diag.formatUsed = diag.cacheHit ? "cache" : "stale-cache";
    }
    return diag;
  }

  // Single resolve pass — do not probe clients twice.
  const resolved = await engine.resolveCaptionTracksResult(id, signal);
  diag.attempts = resolved.attempts;
  diag.clients = resolved.attempts.map((line) => probeFromAttempt(line, true));
  if (resolved.error !== undefined) {
    diag.error = errorText(resolved.error);
    return diag;
  }
  diag.tracks = resolved.tracks.map(briefFromTrack);

  let picked: PickCaptionResult;
  try {
    picked = pickCaptionTrack(resolved.tracks, lang, false);
  } catch (err) {
    diag.error = errorText(err);
    return diag;
  }
  diag.selected = {
    languageCode: picked.resolvedLang,
    source: picked.source,
    translatedFrom: picked.translatedFrom || undefined,
    warnings: picked.warnings.length > 0 ? picked.warnings : undefined,
  };

  let probe: { segments: TranscriptSegment[]; format: string };
  try {
    probe = await probeCaptionBody(engine, picked.captionUrl, signal);
  } catch (err) {
    diag.error = errorText(err);
    return diag;
  }
  diag.formatUsed = probe.format;
  diag.segmentCount = probe.segments.length > 0 ? probe.segments.length : undefined;
  if (probe.segments.length > 0) {
    diag.ok = true;
    diag.bodyBytes = estimateBodyBytes(probe.segments);
  } else {
    diag.error = "EMPTY_TRANSCRIPT: caption body had no segments";
  }
  return diag;
}

/** Tries json3, then srv1/srv3, reporting which format produced segments. */
async function probeCaptionBody(
  engine: Engine,
  baseUrl: string,
  signal?: AbortSignal,
): Promise<{ segments: TranscriptSegment[]; format: string }> {
  let json3Err: unknown = null;
  try {
    const segs = await engine.fetchJSON3(withFormat(baseUrl, "json3"), false, signal);
    if (segs.length > 0) {
      return { segments: segs, format: "json3" };
    }
  } catch (err) {
    if (isExtractError(err) && err.code === "RATE_LIMITED") {
      throw err;
    }
    json3Err = err;
  }
  for (const format of ["srv1", "srv3"]) {
    try {
      const segs = await engine.fetchTimedTextXML(withFormat(baseUrl, format), signal);
      if (segs.length > 0) {
        return { segments: segs, format };
      }
    } catch (err) {
      if (isExtractError(err) && err.code === "RATE_LIMITED") {
        throw err;
      }
    }
  }
  if (json3Err !== null) {
    throw json3Err;
  }
  throw new Error("all caption formats returned empty");
}
