import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { formatTimestamp, parseTimestamp, watchURLAt } from "./timestamps.js";
import { parseVideoID, parsePlaylistID } from "./ids.js";
import { parseLangChain, pickCaptionTrack, mergeASRSegments, normalizeCaptionText, absolutizeCaptionUrl, parseCompactCount, applyEngagementFromNext } from "./transcript.js";
import type { VideoInfo } from "./types.js";
import { parseChapters } from "./chapters.js";
import { pageTranscript } from "./paging.js";
import { buildRAGChunks } from "./rag.js";
import { rankPassages, tokenize } from "./ask.js";
import { ExtractError } from "./errors.js";
import type { CaptionTrack, TranscriptSegment, Transcript } from "./types.js";

describe("timestamps", () => {
  it("formats M:SS and H:MM:SS", () => {
    assert.equal(formatTimestamp(90), "1:30");
    assert.equal(formatTimestamp(3723), "1:02:03");
    assert.equal(formatTimestamp(-1), "0:00");
  });

  it("parses timestamps", () => {
    assert.equal(parseTimestamp("1:30"), 90);
    assert.equal(parseTimestamp("1:02:03"), 3723);
    assert.throws(() => parseTimestamp("bad"), ExtractError);
  });

  it("builds watch URLs", () => {
    assert.equal(watchURLAt("abcdefghijk", 0), "https://www.youtube.com/watch?v=abcdefghijk");
    assert.equal(watchURLAt("abcdefghijk", 12), "https://www.youtube.com/watch?v=abcdefghijk&t=12s");
  });
});

describe("ids", () => {
  it("parses bare IDs and URLs", () => {
    assert.equal(parseVideoID("jNQXAC9IVRw"), "jNQXAC9IVRw");
    assert.equal(parseVideoID("https://www.youtube.com/watch?v=jNQXAC9IVRw"), "jNQXAC9IVRw");
    assert.equal(parseVideoID("https://youtu.be/jNQXAC9IVRw"), "jNQXAC9IVRw");
    assert.equal(parseVideoID("https://www.youtube.com/shorts/jNQXAC9IVRw"), "jNQXAC9IVRw");
    assert.throws(() => parseVideoID("https://vimeo.com/123"), ExtractError);
  });

  it("parses playlist IDs", () => {
    assert.equal(
      parsePlaylistID("https://www.youtube.com/playlist?list=PLtest1234567890"),
      "PLtest1234567890",
    );
  });
});

describe("caption URLs", () => {
  it("absolutizes relative timedtext URLs from watch-page HTML", () => {
    assert.equal(absolutizeCaptionUrl(""), "");
    assert.equal(
      absolutizeCaptionUrl("/api/timedtext?v=abc&lang=en"),
      "https://www.youtube.com/api/timedtext?v=abc&lang=en",
    );
    assert.equal(
      absolutizeCaptionUrl("//www.youtube.com/api/timedtext?v=abc"),
      "https://www.youtube.com/api/timedtext?v=abc",
    );
    assert.equal(
      absolutizeCaptionUrl("https://www.youtube.com/api/timedtext?v=abc"),
      "https://www.youtube.com/api/timedtext?v=abc",
    );
  });
});

describe("engagement counts", () => {
  it("parses compact and full YouTube count strings", () => {
    assert.equal(parseCompactCount("2.4M"), 2_400_000);
    assert.equal(parseCompactCount("19M"), 19_000_000);
    assert.equal(parseCompactCount("208K"), 208_000);
    assert.equal(parseCompactCount("1.7B"), 1_700_000_000);
    assert.equal(parseCompactCount("1,796,960,277"), 1_796_960_277);
    assert.equal(parseCompactCount("2.4M comments"), 2_400_000);
    assert.equal(parseCompactCount(""), 0);
  });

  it("fills commentCount from the Comments engagement panel", () => {
    const info = { id: "x" } as VideoInfo;
    applyEngagementFromNext(info, {
      engagementPanels: [
        {
          engagementPanelSectionListRenderer: {
            header: {
              engagementPanelTitleHeaderRenderer: {
                title: { simpleText: "Comments" },
                contextualInfo: { runs: [{ text: "2.4M" }] },
              },
            },
          },
        },
      ],
    });
    assert.equal(info.commentCount, 2_400_000);
  });
});

describe("lang chain", () => {
  const tracks: CaptionTrack[] = [
    { languageCode: "es", name: "Spanish", isAutoGenerated: false, isTranslatable: false, baseUrl: "http://es" },
    { languageCode: "en", name: "English (auto)", isAutoGenerated: true, isTranslatable: false, baseUrl: "http://en" },
    { languageCode: "en-GB", name: "English UK", isAutoGenerated: false, isTranslatable: true, baseUrl: "http://en-gb" },
  ];

  it("parses preference chains", () => {
    assert.deepEqual(parseLangChain("hi, en,hi"), ["hi", "en"]);
  });

  it("picks manual by default", () => {
    const got = pickCaptionTrack(tracks, "", false);
    assert.equal(got.track.languageCode, "es");
    assert.equal(got.source, "manual");
  });

  it("falls back best-effort with warning", () => {
    // Non-translatable-only set → fallback, not auto-translate.
    const limited = tracks.filter((t) => !t.isTranslatable);
    const got = pickCaptionTrack(limited, "fr", false);
    assert.equal(got.source, "fallback");
    assert.ok((got.warnings?.length ?? 0) > 0);
  });

  it("strict fails on missing language", () => {
    const limited = tracks.filter((t) => !t.isTranslatable);
    assert.throws(() => pickCaptionTrack(limited, "fr", true), (e: unknown) => {
      return e instanceof ExtractError && e.code === "LANGUAGE_NOT_AVAILABLE";
    });
  });

  it("honors preference chain", () => {
    const got = pickCaptionTrack(tracks, "xx,en", false);
    assert.equal(got.resolvedLang, "en");
  });
});

describe("ASR merge", () => {
  it("joins mid-phrase cues", () => {
    const segs: TranscriptSegment[] = [
      { text: "Hello there", start: 0, duration: 2, end: 0, timestamp: "", timestampEnd: "" },
      { text: "my friend", start: 1.8, duration: 2, end: 0, timestamp: "", timestampEnd: "" },
      { text: "Done.", start: 5, duration: 1, end: 0, timestamp: "", timestampEnd: "" },
    ];
    const merged = mergeASRSegments(segs);
    assert.ok(merged.length <= 3);
    assert.ok(merged.some((s) => s.text.includes("Hello")));
  });
});

describe("chapters", () => {
  it("parses ascending description chapters", () => {
    const ch = parseChapters("0:00 Intro\n1:30 Next\n12:45 Deep", 4000);
    assert.equal(ch.length, 3);
    assert.equal(ch[0]!.title, "Intro");
    assert.equal(ch[1]!.startSeconds, 90);
  });

  it("rejects chapters that do not start at 0", () => {
    assert.equal(parseChapters("1:00 Intro\n2:00 Next", 4000).length, 0);
  });
});

describe("paging", () => {
  it("pages without splitting segments", () => {
    const segments = [
      { text: "aaaa", start: 0, duration: 1, end: 1, timestamp: "0:00", timestampEnd: "0:01" },
      { text: "bbbb", start: 1, duration: 1, end: 2, timestamp: "0:01", timestampEnd: "0:02" },
      { text: "cccc", start: 2, duration: 1, end: 3, timestamp: "0:02", timestampEnd: "0:03" },
    ];
    const tr: Transcript = {
      videoId: "abcdefghijk",
      languageCode: "en",
      languageName: "English",
      isAutoGenerated: false,
      merged: false,
      rawSegmentCount: 3,
      segmentCount: 3,
      durationSeconds: 3,
      segments,
      lines: segments.map((s) => `[${s.timestamp}] ${s.text}`),
      text: "aaaa bbbb cccc",
    };
    const page = pageTranscript(tr, 0, 6);
    assert.equal(page.hasMore, true);
    assert.ok(page.nextCursor! > 0);
    assert.equal(page.totalSegments, 3);
  });
});

describe("rag + ask", () => {
  it("builds citation chunks", () => {
    const segs: TranscriptSegment[] = [
      { text: "Elephants are cool animals.", start: 0, duration: 5, end: 5, timestamp: "0:00", timestampEnd: "0:05" },
      { text: "They live in Africa and Asia.", start: 5, duration: 5, end: 10, timestamp: "0:05", timestampEnd: "0:10" },
    ];
    const chunks = buildRAGChunks("abcdefghijk", segs, 40);
    assert.ok(chunks.length >= 1);
    assert.ok(chunks[0]!.citation);
    assert.ok(chunks[0]!.url.includes("watch?v="));
  });

  it("ranks passages", () => {
    const chunks = buildRAGChunks(
      "abcdefghijk",
      [
        { text: "Elephants are cool animals in the zoo.", start: 0, duration: 5, end: 5, timestamp: "0:00", timestampEnd: "0:05" },
        { text: "Cars drive fast on the highway.", start: 5, duration: 5, end: 10, timestamp: "0:05", timestampEnd: "0:10" },
      ],
      80,
    );
    const ranked = rankPassages(chunks, "cool elephants zoo", 2);
    assert.ok(ranked.length >= 1);
    assert.ok(tokenize("cool elephants").length >= 1);
  });
});

describe("normalize", () => {
  it("collapses whitespace", () => {
    assert.equal(normalizeCaptionText("hello\n  world"), "hello world");
  });
});
