/**
 * Transcript clipping, search, and subtitle export.
 * Ported from internal/youtube/subtitles.go.
 */
import { writeFile } from "node:fs/promises";

import { ExtractError } from "./errors.js";
import { formatTimestamp } from "./timestamps.js";
import { buildTranscript, type Engine } from "./transcript.js";
import type {
  SubtitleExport,
  SubtitleFormat,
  Transcript,
  TranscriptHit,
  TranscriptSearchResult,
  TranscriptSegment,
} from "./types.js";

export type { SubtitleExport, TranscriptHit, TranscriptSearchResult } from "./types.js";

const SUBTITLE_FORMATS: SubtitleFormat[] = ["srt", "vtt", "ass", "json", "text", "chapters"];

function asSubtitleFormat(value: string): SubtitleFormat | undefined {
  return SUBTITLE_FORMATS.find((f) => f === value);
}

/** Returns only the segments overlapping [start, end] seconds. */
export async function transcriptClip(
  engine: Engine,
  input: string,
  lang: string | undefined,
  start: number,
  end: number,
  signal?: AbortSignal,
): Promise<Transcript> {
  if (end > 0 && end <= start) {
    throw new ExtractError({
      code: "INVALID_RANGE",
      message: "endSeconds must be greater than startSeconds",
    });
  }
  const tr = await engine.transcript(input, lang, signal);
  const clipped: TranscriptSegment[] = [];
  for (const s of tr.segments) {
    if (s.end <= start) {
      continue;
    }
    if (end > 0 && s.start >= end) {
      continue;
    }
    clipped.push(s);
  }
  if (clipped.length === 0) {
    throw new ExtractError({
      code: "EMPTY_CLIP",
      message: `No transcript segments overlap the range ${formatTimestamp(start)}–${formatTimestamp(end)}`,
      details: { start, end },
    });
  }
  const track = {
    languageCode: tr.languageCode,
    name: tr.languageName,
    isAutoGenerated: tr.isAutoGenerated,
  };
  // Clipped rows are already presentation segments; don't merge again.
  const out = buildTranscript(
    tr.videoId,
    track,
    clipped,
    false,
    tr.translatedFrom ?? "",
    tr.source ?? "",
    tr.requestedLang ?? "",
    undefined,
  );
  out.merged = tr.merged;
  return out;
}

/** Finds segments containing `query` (case-insensitive). */
export async function searchTranscript(
  engine: Engine,
  input: string,
  lang: string | undefined,
  query: string,
  contextWindow: number,
  signal?: AbortSignal,
): Promise<TranscriptSearchResult> {
  const trimmed = query.trim();
  if (trimmed === "") {
    throw new ExtractError({ code: "USAGE", message: "search query must not be empty" });
  }
  const tr = await engine.transcript(input, lang, signal);
  let window = contextWindow;
  if (window < 0) {
    window = 0;
  }
  if (window > 5) {
    window = 5;
  }
  const q = trimmed.toLowerCase();
  const hits: TranscriptHit[] = [];
  tr.segments.forEach((s, i) => {
    if (!s.text.toLowerCase().includes(q)) {
      return;
    }
    const from = Math.max(0, i - window);
    const to = Math.min(tr.lines.length, i + window + 1);
    hits.push({ segment: s, index: i, context: tr.lines.slice(from, to) });
  });
  return { videoId: tr.videoId, query: trimmed, matchCount: hits.length, hits };
}

/** Renders captions in the requested format (srt|vtt|ass|json|text|chapters). */
export async function exportSubtitles(
  engine: Engine,
  input: string,
  lang: string | undefined,
  format: string,
  outPath: string,
  signal?: AbortSignal,
): Promise<SubtitleExport> {
  const requested = (format ?? "").trim().toLowerCase();
  const fmt = asSubtitleFormat(requested === "" ? "srt" : requested);
  if (fmt === undefined) {
    throw new ExtractError({
      code: "INVALID_FORMAT",
      message: `Unsupported subtitle format "${requested}"; use srt, vtt, ass, json, text, or chapters`,
    });
  }
  const tr = await engine.transcriptWithOptions(
    input,
    { lang, groupByChapters: fmt === "chapters" },
    signal,
  );

  let body: string;
  switch (fmt) {
    case "srt":
      body = toSRT(tr.segments);
      break;
    case "vtt":
      body = toVTT(tr.segments);
      break;
    case "ass":
      body = toASS(tr.segments);
      break;
    case "json":
      body = JSON.stringify(tr, null, 2);
      break;
    case "text":
      body = tr.lines.join("\n");
      break;
    case "chapters": {
      const chapters = tr.chapters ?? [];
      if (chapters.length === 0) {
        body = tr.lines.join("\n");
        break;
      }
      let out = "";
      for (const ch of chapters) {
        out += `## [${ch.timestamp}] ${ch.title}\n${ch.url}\n\n`;
        for (const s of ch.segments) {
          out += `[${s.timestamp}] ${s.text}\n`;
        }
        out += "\n";
      }
      body = out;
      break;
    }
  }

  const result: SubtitleExport = {
    videoId: tr.videoId,
    format: fmt,
    languageCode: tr.languageCode,
    segmentCount: tr.segmentCount,
    content: body,
    source: tr.source,
  };
  if (tr.warnings && tr.warnings.length > 0) {
    result.warnings = tr.warnings;
  }
  if (outPath !== "") {
    try {
      await writeFile(outPath, body, { mode: 0o644 });
    } catch (err) {
      throw new ExtractError({
        code: "WRITE_ERROR",
        message: "Could not write subtitle file: " + (err as Error).message,
      });
    }
    result.path = outPath;
  }
  return result;
}

function pad(n: number, width: number): string {
  return String(n).padStart(width, "0");
}

export function srtTime(seconds: number): string {
  const clamped = seconds < 0 ? 0 : seconds;
  const totalMs = Math.floor(clamped * 1000 + 0.5);
  const h = Math.floor(totalMs / 3_600_000);
  const m = Math.floor((totalMs % 3_600_000) / 60_000);
  const s = Math.floor((totalMs % 60_000) / 1000);
  const ms = totalMs % 1000;
  return `${pad(h, 2)}:${pad(m, 2)}:${pad(s, 2)},${pad(ms, 3)}`;
}

export function vttTime(seconds: number): string {
  return srtTime(seconds).replace(",", ".");
}

export function assTime(seconds: number): string {
  const clamped = seconds < 0 ? 0 : seconds;
  const totalCs = Math.floor(clamped * 100 + 0.5);
  const h = Math.floor(totalCs / 360000);
  const m = Math.floor((totalCs % 360000) / 6000);
  const s = Math.floor((totalCs % 6000) / 100);
  const cs = totalCs % 100;
  return `${h}:${pad(m, 2)}:${pad(s, 2)}.${pad(cs, 2)}`;
}

export function toSRT(segments: TranscriptSegment[]): string {
  let out = "";
  segments.forEach((s, i) => {
    out += `${i + 1}\n${srtTime(s.start)} --> ${srtTime(s.end)}\n${s.text}\n\n`;
  });
  return out;
}

export function toVTT(segments: TranscriptSegment[]): string {
  let out = "WEBVTT\n\n";
  for (const s of segments) {
    out += `${vttTime(s.start)} --> ${vttTime(s.end)}\n${s.text}\n\n`;
  }
  return out;
}

export function toASS(segments: TranscriptSegment[]): string {
  let out = "[Script Info]\nTitle: YouTube Client export\nScriptType: v4.00+\n\n";
  out += "[V4+ Styles]\n";
  out +=
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n";
  out +=
    "Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1\n\n";
  out += "[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n";
  for (const s of segments) {
    out += `Dialogue: 0,${assTime(s.start)},${assTime(s.end)},Default,,0,0,0,,${s.text}\n`;
  }
  return out;
}
