/**
 * Transcript pipeline: InnerTube player fetch, caption track resolution,
 * timedtext download (json3 / srv1 / srv3), ASR sentence merging, and the
 * `Engine` facade the rest of the modules hang off.
 *
 * Ported from internal/youtube/{extractor,captions,timedtext}.go. JSON shapes
 * match the Go structs field-for-field, including `omitempty` behaviour: fields
 * Go omits when zero are left `undefined` here so `JSON.stringify` drops them.
 */
import { setTimeout as sleep } from "node:timers/promises";

import {
  ExtractError,
  classifyNetworkError,
  httpStatusError,
  isExtractError,
} from "./errors.js";
import { parseVideoId, watchUrlAt } from "./ids.js";
import {
  MAX_RETRIES,
  WEB_USER_AGENT,
  captionClients,
  clientANDROID,
  clientIOS,
  clientWEB,
  playerClients,
  type Client,
  type InnertubeProfile,
} from "./innertube.js";
import {
  assertTimedtextAllowed,
  isTimedtextCoolingDown,
  markTimedtextRateLimited,
} from "./timedtext-gate.js";
import { formatTimestamp } from "./timestamps.js";
import type {
  AskOptions,
  AskResult,
  BatchOptions,
  BatchPack,
  CaptionTrack,
  Chapter,
  ChapterGroup,
  ChaptersResult,
  ChannelResult,
  CommentsOptions,
  CommentsResult,
  DownloadResult,
  HeatmapResult,
  ManifestsResult,
  PackOptions,
  PlaylistResult,
  SearchResults,
  SponsorSegment,
  StoryboardsResult,
  Thumbnail,
  Transcript,
  TranscriptDiagnosis,
  TranscriptOptions,
  TranscriptPage,
  TranscriptSearchResult,
  TranscriptSegment,
  TranscriptSource,
  TranscriptWord,
  SubtitleExport,
  VideoInfo,
  VideoPack,
} from "./types.js";

import { askVideo as askVideoFor } from "./ask.js";
import { batchPackFor } from "./batch.js";
import { chaptersFor } from "./chapters.js";
import { commentsWithOptions as commentsFor } from "./comments.js";
import {
  channelPreferAPI as channelPreferAPIFor,
  searchPreferAPI as searchPreferAPIFor,
  type ChannelPreferResult,
  type SearchPreferResult,
} from "./dataapi.js";
import { diagnoseTranscript } from "./diagnose.js";
import {
  channel as channelFor,
  playlist as playlistFor,
  search as searchFor,
} from "./discovery.js";
import {
  heatmap as heatmapFor,
  manifests as manifestsFor,
  related as relatedFor,
  storyboards as storyboardsFor,
  type RelatedResultWithCache,
} from "./extras.js";
import { downloadMedia, listFormats, type FormatsResult } from "./media.js";
import { pageTranscript } from "./paging.js";
import { videoPackWithOptions as videoPackFor } from "./rag.js";
import { sponsorSegments as sponsorSegmentsFor } from "./sponsorblock.js";
import { exportSubtitles, searchTranscript, transcriptClip } from "./subtitles.js";

export type { TranscriptOptions } from "./types.js";

/** Raw `captionTracks[]` entry from the player response. */
export interface RawCaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  isTranslatable?: boolean;
  name?: { simpleText?: string; runs?: Array<{ text?: string }> };
}

/** Raw `streamingData.formats[]` / `adaptiveFormats[]` entry. */
export interface RawFormat {
  itag?: number;
  url?: string;
  signatureCipher?: string;
  mimeType?: string;
  bitrate?: number;
  quality?: string;
  qualityLabel?: string;
  audioQuality?: string;
  contentLength?: string;
}

/** The subset of the InnerTube `player` response this engine reads. */
export interface PlayerResponse {
  playabilityStatus?: {
    status?: string;
    reason?: string;
    errorScreen?: {
      playerErrorMessageRenderer?: { reason?: { simpleText?: string } };
    };
  };
  videoDetails?: {
    videoId?: string;
    title?: string;
    lengthSeconds?: string;
    keywords?: string[];
    channelId?: string;
    shortDescription?: string;
    viewCount?: string;
    author?: string;
    isLiveContent?: boolean;
    thumbnail?: { thumbnails?: Thumbnail[] };
  };
  microformat?: {
    playerMicroformatRenderer?: {
      publishDate?: string;
      uploadDate?: string;
      category?: string;
      likeCount?: string;
      isFamilySafe?: boolean;
      isUnlisted?: boolean;
      availableCountries?: string[];
      ownerProfileUrl?: string;
      embed?: { iframeUrl?: string };
    };
  };
  captions?: {
    playerCaptionsTracklistRenderer?: { captionTracks?: RawCaptionTrack[] };
  };
  streamingData?: {
    formats?: RawFormat[];
    adaptiveFormats?: RawFormat[];
    dashManifestUrl?: string;
    hlsManifestUrl?: string;
  };
  storyboards?: {
    playerStoryboardSpecRenderer?: { spec?: string };
  };
}

/** Public caption track summary — signed URLs are never exposed. */
export interface CaptionTrackSummary {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
  sourceClient?: string;
}

/** Merged caption track list for one video plus per-client diagnostics. */
export interface ResolvedCaptions {
  tracks: CaptionTrack[];
  attempts: string[];
  clients: string[];
}

/** `resolveCaptionTracks` without throwing, so diagnostics keep the attempts. */
export interface ResolvedCaptionsResult extends ResolvedCaptions {
  error?: ExtractError;
}

/** Outcome of language-chain resolution. */
export interface PickCaptionResult {
  track: CaptionTrack;
  captionUrl: string;
  translatedFrom: string;
  source: TranscriptSource;
  warnings: string[];
  resolvedLang: string;
}

const SOUND_TAG_PATTERN = /^\[[^\]]+\]$/;
const FMT_PARAM_PATTERN = /fmt=\w+/;
const TLANG_PARAM_PATTERN = /tlang=[^&]*/;

function env(name: string): string {
  return (process.env[name] ?? "").trim();
}

/** Go's `error.Error()` for ExtractError is "CODE: message"; mirror that. */
export function errorText(err: unknown): string {
  if (isExtractError(err)) {
    return `${err.code}: ${err.message}`;
  }
  if (err instanceof Error) {
    return err.message;
  }
  return String(err);
}

/** Reports whether a failure is worth rescuing from stale cache. */
export function isRetryableExtract(err: unknown): boolean {
  if (err === null || err === undefined) {
    return false;
  }
  if (!isExtractError(err)) {
    return true;
  }
  switch (err.code) {
    case "RATE_LIMITED":
    case "RATE_BUDGET_EXCEEDED":
    case "NETWORK_ERROR":
    case "TIMEOUT":
    case "EMPTY_TRANSCRIPT":
    case "CAPTION_PARSE_ERROR":
    case "YOUTUBE_HTTP_ERROR":
    case "ACCESS_DENIED":
      return true;
    default:
      return err.retryable;
  }
}

function mergeDetails(
  a: Record<string, unknown> | undefined,
  b: Record<string, unknown> | undefined,
): Record<string, unknown> {
  return { ...(a ?? {}), ...(b ?? {}) };
}

function captionDisplayName(t: RawCaptionTrack): string {
  if (t.name?.simpleText) {
    return t.name.simpleText;
  }
  return (t.name?.runs ?? []).map((run) => run.text ?? "").join("");
}

export function captionsFromPlayer(p: PlayerResponse): CaptionTrack[] {
  const raw = p.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return raw.map((t) => ({
    languageCode: t.languageCode ?? "",
    name: captionDisplayName(t),
    isAutoGenerated: t.kind === "asr",
    isTranslatable: t.isTranslatable === true,
    baseUrl: t.baseUrl ?? "",
    altUrls: [],
  }));
}

export function toCaptionTrackSummary(t: CaptionTrack): CaptionTrackSummary {
  return {
    languageCode: t.languageCode,
    name: t.name,
    isAutoGenerated: t.isAutoGenerated,
    isTranslatable: t.isTranslatable,
    sourceClient: t.sourceClient ? t.sourceClient : undefined,
  };
}

export function classifyPlayabilityFailure(videoId: string, attempts: string[]): ExtractError {
  const joined = attempts.join(" | ").toLowerCase();
  let code = "VIDEO_UNAVAILABLE";
  let message = "YouTube did not return a playable response for this video";
  let retryable = false;
  if (joined.includes("login_required") || joined.includes("sign in") || joined.includes("age")) {
    code = "AUTH_REQUIRED";
    message =
      "This video requires sign-in or age verification; pass cookies via --cookies or YTUBE_COOKIES";
  } else if (joined.includes("private")) {
    code = "PRIVATE_VIDEO";
    message = "This video is private";
  } else if (joined.includes("unavailable") || joined.includes("removed")) {
    code = "VIDEO_UNAVAILABLE";
    message = "This video is unavailable (deleted, region-blocked, or the ID does not exist)";
  } else if (joined.includes("rate") || joined.includes("429")) {
    code = "RATE_LIMITED";
    retryable = true;
    message = "YouTube rate-limited the request; wait a few minutes and retry";
  } else if (joined.includes("live")) {
    code = "LIVE_NOT_SUPPORTED";
    message = "Live streams are not supported by this extractor";
  }
  return new ExtractError({
    code,
    message,
    retryable,
    details: { videoId, attempts },
  });
}

export function infoFromPlayer(id: string, p: PlayerResponse): VideoInfo {
  const details = p.videoDetails ?? {};
  const micro = p.microformat?.playerMicroformatRenderer ?? {};
  const duration = parseIntOr0(details.lengthSeconds);
  const views = parseIntOr0(details.viewCount);
  let channelUrl = micro.ownerProfileUrl ?? "";
  if (!channelUrl && details.channelId) {
    channelUrl = "https://www.youtube.com/channel/" + details.channelId;
  }
  const countries = micro.availableCountries?.length ?? 0;
  return {
    id,
    url: "https://www.youtube.com/watch?v=" + id,
    title: details.title ?? "",
    description: details.shortDescription ?? "",
    channelId: details.channelId ?? "",
    channelName: details.author ?? "",
    channelUrl: channelUrl || undefined,
    durationSeconds: duration,
    duration: formatTimestamp(duration),
    viewCount: views || undefined,
    publishDate: micro.publishDate || undefined,
    uploadDate: micro.uploadDate || undefined,
    category: micro.category || undefined,
    keywords: details.keywords?.length ? details.keywords : undefined,
    isLive: details.isLiveContent === true,
    isUnlisted: micro.isUnlisted === true ? true : undefined,
    isFamilySafe: micro.isFamilySafe === true,
    availableCountryCount: countries || undefined,
    embedUrl: micro.embed?.iframeUrl || undefined,
    thumbnails: details.thumbnail?.thumbnails ?? [],
  };
}

function parseIntOr0(value: string | undefined): number {
  if (!value) {
    return 0;
  }
  const n = Number.parseInt(value, 10);
  return Number.isFinite(n) ? n : 0;
}

export function parseLangChain(lang: string | undefined): string[] {
  const trimmed = (lang ?? "").trim();
  if (trimmed === "") {
    return [];
  }
  const out: string[] = [];
  const seen = new Set<string>();
  for (const part of trimmed.split(",")) {
    const p = part.trim().toLowerCase();
    if (p === "" || seen.has(p)) {
      continue;
    }
    seen.add(p);
    out.push(p);
  }
  return out;
}

export function langBase(code: string): string {
  const lower = code.toLowerCase();
  const i = lower.indexOf("-");
  return i > 0 ? lower.slice(0, i) : lower;
}

export function sourceOf(t: CaptionTrack): TranscriptSource {
  return t.isAutoGenerated ? "asr" : "manual";
}

/** The signed timedtext endpoint for a track, or "" when the client withheld it. */
export function trackBaseUrl(t: CaptionTrack): string {
  return t.baseUrl ?? "";
}

/** Alternate client signatures collected for empty-body escalation. */
export function trackAltUrls(t: CaptionTrack): string[] {
  return t.altUrls ?? [];
}

function pickResult(
  track: CaptionTrack,
  source: TranscriptSource,
  warnings: string[] = [],
): PickCaptionResult {
  return {
    track,
    captionUrl: trackBaseUrl(track),
    translatedFrom: "",
    source,
    warnings,
    resolvedLang: track.languageCode,
  };
}

function matchLang(tracks: CaptionTrack[], want: string): PickCaptionResult | null {
  const target = want.toLowerCase();
  let exactAsr: CaptionTrack | null = null;
  let prefix: CaptionTrack | null = null;
  let baseMatch: CaptionTrack | null = null;
  for (const track of tracks) {
    const code = track.languageCode.toLowerCase();
    if (code === target && !track.isAutoGenerated) {
      return pickResult(track, "manual");
    }
    if (code === target && exactAsr === null) {
      exactAsr = track;
    } else if (code.startsWith(target + "-") && prefix === null) {
      prefix = track;
    } else if (langBase(code) === target && baseMatch === null) {
      baseMatch = track;
    } else if (langBase(target) === code && baseMatch === null) {
      // requested "en-US", available "en"
      baseMatch = track;
    }
  }
  const pick = exactAsr ?? prefix ?? baseMatch;
  if (pick === null) {
    return null;
  }
  return pickResult(pick, sourceOf(pick));
}

function altTranslateUrls(base: CaptionTrack, target: string): string[] {
  return trackAltUrls(base).map((u) => withTranscriptLang(u, target));
}

/**
 * Selects the best track for a language preference chain. Order per requested
 * entry: exact manual > exact ASR > regional variant > base-of-regional. Then
 * auto-translate from any translatable track. Then the first available track
 * (fallback) unless strict.
 */
export function pickCaptionTrack(
  tracks: CaptionTrack[],
  lang: string | undefined,
  strict: boolean,
): PickCaptionResult {
  if (tracks.length === 0) {
    throw new ExtractError({
      code: "NO_CAPTIONS",
      message:
        "This video has no caption tracks (the uploader disabled them or YouTube has not generated any)",
    });
  }
  const chain = parseLangChain(lang);
  if (chain.length === 0) {
    for (const track of tracks) {
      if (!track.isAutoGenerated) {
        return pickResult(track, "manual");
      }
    }
    return pickResult(tracks[0]!, sourceOf(tracks[0]!));
  }

  const available = tracks.map((t) => t.languageCode);

  for (const want of chain) {
    const result = matchLang(tracks, want);
    if (result !== null) {
      return result;
    }
  }

  // Strict mode: never invent a translate/fallback track.
  if (strict) {
    throw new ExtractError({
      code: "LANGUAGE_NOT_AVAILABLE",
      message: `No caption track for language "${lang ?? ""}"; available languages: ${available.join(", ")}`,
      details: { requested: lang ?? "", available },
    });
  }

  // Auto-translate from the first translatable track to the first requested lang.
  const target = chain[0]!;
  for (const track of tracks) {
    if (!track.isTranslatable) {
      continue;
    }
    const url = withTranscriptLang(trackBaseUrl(track), target);
    return {
      track: {
        languageCode: target,
        name: track.name,
        isAutoGenerated: true,
        isTranslatable: true,
        baseUrl: url,
        altUrls: altTranslateUrls(track, target),
        sourceClient: track.sourceClient,
      },
      captionUrl: url,
      translatedFrom: track.languageCode,
      source: "translated",
      resolvedLang: target,
      warnings: [
        `No native "${target}" track; using YouTube auto-translate from "${track.languageCode}"`,
      ],
    };
  }

  // Best-effort: serve whatever exists.
  let fallback = tracks[0]!;
  for (const track of tracks) {
    if (!track.isAutoGenerated) {
      fallback = track;
      break;
    }
  }
  return {
    ...pickResult(fallback, "fallback"),
    warnings: [`Requested "${lang ?? ""}" unavailable; falling back to "${fallback.languageCode}"`],
  };
}

export function enrichSegments(segments: TranscriptSegment[]): TranscriptSegment[] {
  return segments.map((s) => {
    let end = s.end ?? 0;
    if (end <= 0) {
      end = s.start + s.duration;
    }
    if (end < s.start) {
      end = s.start;
    }
    let words: TranscriptWord[] | undefined;
    if (s.words && s.words.length > 0) {
      words = s.words.map((w) => ({ ...w, timestamp: formatTimestamp(w.start) }));
    }
    return {
      text: s.text,
      start: s.start,
      duration: end - s.start,
      end,
      timestamp: formatTimestamp(s.start),
      timestampEnd: formatTimestamp(end),
      words,
    };
  });
}

/** Reports whether text already finishes a sentence/cue cleanly. */
export function sentenceEnd(text: string): boolean {
  const trimmed = text.trim();
  if (trimmed === "") {
    return false;
  }
  const runes = [...trimmed];
  const last = runes[runes.length - 1]!;
  switch (last) {
    case ".":
    case "!":
    case "?":
    case "।":
    case "؟":
    case "…":
    case "♪":
      return true;
    case "]": // e.g. [संगीत] / [music]
      return true;
    default:
      return false;
  }
}

/**
 * Joins YouTube ASR's mid-phrase cue fragments into readable sentences.
 * Official timedtext is already complete; ASR chops speech into ~2-4s windows
 * that often end mid-sentence.
 */
export function mergeASRSegments(segments: TranscriptSegment[]): TranscriptSegment[] {
  if (segments.length <= 1) {
    return enrichSegments(segments);
  }
  const enriched = enrichSegments(segments);
  const maxGap = 1.75;
  const maxDuration = 45.0;
  const maxChars = 500;

  const out: TranscriptSegment[] = [];
  let cur = { ...enriched[0]! };
  for (let i = 1; i < enriched.length; i++) {
    const next = enriched[i]!;
    const span = next.end - cur.start;
    const chars = [...cur.text].length + 1 + [...next.text].length;
    // ASR cues often overlap in time (rolling windows) while carrying the NEXT
    // phrase only — allow small overlaps and short gaps.
    const nearby = next.start <= cur.end + maxGap && next.start >= cur.start - 0.05;
    if (!sentenceEnd(cur.text) && nearby && span <= maxDuration && chars <= maxChars) {
      cur.text = (cur.text + " " + next.text).trim();
      if (next.end > cur.end) {
        cur.end = next.end;
      }
      cur.duration = cur.end - cur.start;
      continue;
    }
    out.push(cur);
    cur = { ...next };
  }
  out.push(cur);
  return enrichSegments(out);
}

export function buildTranscript(
  id: string,
  track: { languageCode: string; name: string; isAutoGenerated: boolean },
  segments: TranscriptSegment[],
  merged: boolean,
  translatedFrom: string,
  source: TranscriptSource | "",
  requestedLang: string,
  warnings: string[] | undefined,
): Transcript {
  const rawCount = segments.length;
  const finalSegments = merged ? mergeASRSegments(segments) : enrichSegments(segments);

  const lines: string[] = [];
  const textParts: string[] = [];
  let duration = 0;
  for (const s of finalSegments) {
    lines.push("[" + s.timestamp + "] " + s.text);
    textParts.push(s.text);
    if (s.end > duration) {
      duration = s.end;
    }
  }

  let name = track.name;
  if (translatedFrom !== "") {
    name = name + " (translated to " + track.languageCode + ")";
  }
  let resolvedSource: TranscriptSource | "" = source;
  if (resolvedSource === "") {
    resolvedSource = track.isAutoGenerated ? "asr" : "manual";
    if (translatedFrom !== "") {
      resolvedSource = "translated";
    }
  }

  // Key order mirrors the Go struct so serialized output is byte-comparable.
  return {
    videoId: id,
    languageCode: track.languageCode,
    languageName: name,
    requestedLang: requestedLang || undefined,
    resolvedLang: track.languageCode || undefined,
    source: resolvedSource || undefined,
    isAutoGenerated: track.isAutoGenerated,
    translatedFrom: translatedFrom || undefined,
    merged,
    rawSegmentCount: rawCount,
    segmentCount: finalSegments.length,
    durationSeconds: duration,
    segments: finalSegments,
    lines,
    text: textParts.join(" "),
    warnings: warnings && warnings.length > 0 ? warnings : undefined,
  };
}

export function soundTagOnly(text: string): boolean {
  return SOUND_TAG_PATTERN.test(text.trim());
}

export function stripSoundTagSegments(segments: TranscriptSegment[]): TranscriptSegment[] {
  return segments.filter((s) => !soundTagOnly(s.text.trim()));
}

export function groupSegmentsByChapters(
  videoId: string,
  segments: TranscriptSegment[],
  chapters: Chapter[],
): ChapterGroup[] {
  if (chapters.length === 0) {
    return [];
  }
  const groups: ChapterGroup[] = chapters.map((ch) => ({
    title: ch.title,
    startSeconds: ch.startSeconds,
    timestamp: ch.timestamp,
    url: watchUrlAt(videoId, ch.startSeconds),
    segments: [],
    text: "",
  }));
  for (const s of segments) {
    let idx = 0;
    for (let i = chapters.length - 1; i >= 0; i--) {
      if (s.start >= chapters[i]!.startSeconds) {
        idx = i;
        break;
      }
    }
    groups[idx]!.segments.push(s);
  }
  for (const group of groups) {
    group.text = group.segments.map((s) => s.text).join(" ");
  }
  return groups;
}

export function withTranscriptLang(baseUrl: string, lang: string): string {
  if (lang === "") {
    return baseUrl;
  }
  if (baseUrl.includes("tlang=")) {
    return baseUrl.replace(new RegExp(TLANG_PARAM_PATTERN.source, "g"), "tlang=" + lang);
  }
  const sep = baseUrl.includes("?") ? "&" : "?";
  return baseUrl + sep + "tlang=" + lang;
}

/**
 * Appends `pot=…&c=WEB` when YTUBE_PO_TOKEN is set. Caption GETs are
 * increasingly gated on BotGuard attestation; the player POST already carries
 * the token, but the timedtext URL often needs it too.
 */
export function withPOToken(baseUrl: string): string {
  const pot = env("YTUBE_PO_TOKEN");
  if (pot === "") {
    return baseUrl;
  }
  let sep = baseUrl.includes("?") ? "&" : "?";
  let out = baseUrl;
  if (!baseUrl.includes("pot=")) {
    out += sep + "pot=" + pot;
    sep = "&";
  }
  if (!out.includes("c=")) {
    out += sep + "c=WEB";
  }
  return out;
}

export function appendUniqueUrl(list: string[], u: string): string[] {
  if (u === "") {
    return list;
  }
  if (list.includes(u)) {
    return list;
  }
  return [...list, u];
}

function annotateStale(
  stale: { value: Transcript; ageSeconds: number },
  reason: string,
): Transcript {
  const transcript = { ...stale.value };
  transcript.stale = true;
  transcript.staleAgeSeconds = stale.ageSeconds;
  transcript.warnings = [
    ...(transcript.warnings ?? []),
    `Served stale transcript (${stale.ageSeconds}s old) — ${reason}`,
  ];
  return transcript;
}

export function transcriptCacheKey(id: string, opts: TranscriptOptions): string {
  const merge = opts.merge === undefined ? "auto" : String(opts.merge);
  return [
    id,
    opts.lang ?? "",
    opts.translateTo ?? "",
    merge,
    `strict=${opts.strict === true}`,
    `words=${opts.words === true}`,
    `strip=${opts.stripSoundTags === true}`,
    `chapters=${opts.groupByChapters === true}`,
  ].join("|");
}

export function captionsCacheKey(
  id: string,
  languageCode: string,
  asr: boolean,
  translateTo: string,
  words: boolean,
): string {
  return [id, languageCode, asr ? "asr" : "manual", translateTo, `words=${words}`].join("|");
}

function shouldMerge(opts: TranscriptOptions, auto: boolean): boolean {
  if (opts.merge !== undefined) {
    return opts.merge;
  }
  return auto; // ASR cues are mid-phrase by default; manual tracks usually aren't
}

export function normalizeCaptionText(s: string): string {
  return s.replace(/\n/g, " ").split(/\s+/).filter(Boolean).join(" ");
}

const NAMED_ENTITIES: Record<string, string> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  nbsp: "\u00a0",
  ndash: "\u2013",
  mdash: "\u2014",
  hellip: "\u2026",
  lsquo: "\u2018",
  rsquo: "\u2019",
  ldquo: "\u201c",
  rdquo: "\u201d",
  bull: "\u2022",
  middot: "\u00b7",
  laquo: "\u00ab",
  raquo: "\u00bb",
  deg: "\u00b0",
  eacute: "\u00e9",
  copy: "\u00a9",
  reg: "\u00ae",
  trade: "\u2122",
};

/**
 * Decodes one round of XML/HTML character references. YouTube double-escapes
 * caption text, and Go's pipeline unescapes twice (XML decode then
 * html.UnescapeString), so callers apply this twice as well.
 */
function unescapeEntities(s: string): string {
  if (!s.includes("&")) {
    return s;
  }
  return s.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z][a-zA-Z0-9]*);/g, (match, body: string) => {
    if (body.startsWith("#x") || body.startsWith("#X")) {
      const code = Number.parseInt(body.slice(2), 16);
      return Number.isFinite(code) && code > 0 ? safeFromCodePoint(code, match) : match;
    }
    if (body.startsWith("#")) {
      const code = Number.parseInt(body.slice(1), 10);
      return Number.isFinite(code) && code > 0 ? safeFromCodePoint(code, match) : match;
    }
    const named = NAMED_ENTITIES[body.toLowerCase()];
    return named ?? match;
  });
}

function safeFromCodePoint(code: number, fallback: string): string {
  try {
    return String.fromCodePoint(code);
  } catch {
    return fallback;
  }
}

function decodeCaptionBody(s: string): string {
  return unescapeEntities(unescapeEntities(s));
}

function attr(rawAttrs: string, name: string): string {
  const match = new RegExp(`\\b${name}\\s*=\\s*("([^"]*)"|'([^']*)')`).exec(rawAttrs);
  if (match === null) {
    return "";
  }
  return match[2] ?? match[3] ?? "";
}

function attrFloat(rawAttrs: string, name: string): number {
  const value = attr(rawAttrs, name);
  if (value === "") {
    return 0;
  }
  const n = Number.parseFloat(value);
  return Number.isFinite(n) ? n : 0;
}

interface Json3Segment {
  utf8?: string;
  tOffsetMs?: number;
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  aAppend?: unknown;
  segs?: Json3Segment[];
}

interface Json3Body {
  events?: Json3Event[];
}

/** Combines a request timeout with the caller's cancellation signal. */
function anySignal(timeout: AbortSignal, caller?: AbortSignal): AbortSignal {
  if (caller === undefined) {
    return timeout;
  }
  if (typeof AbortSignal.any === "function") {
    return AbortSignal.any([timeout, caller]);
  }
  const controller = new AbortController();
  for (const signal of [timeout, caller]) {
    if (signal.aborted) {
      controller.abort(signal.reason);
      break;
    }
    signal.addEventListener("abort", () => controller.abort(signal.reason), { once: true });
  }
  return controller.signal;
}

/** `aAppend` rows are karaoke window advances (often just "\n"), not new cues. */
function isAppendEvent(v: unknown): boolean {
  if (typeof v === "boolean") {
    return v;
  }
  if (typeof v === "number") {
    return v !== 0;
  }
  if (typeof v === "string") {
    return v === "1" || v.toLowerCase() === "true";
  }
  return false;
}

/** The in-process YouTube extraction engine. */
export class Engine {
  constructor(readonly client: Client) {}

  // ---------------------------------------------------------------- player

  /**
   * Tries each InnerTube client until one returns a playable response,
   * mirroring yt-dlp's client-fallback strategy.
   */
  async fetchPlayer(
    videoId: string,
    signal?: AbortSignal,
  ): Promise<{ player: PlayerResponse; clientName: string }> {
    const attempts: string[] = [];
    for (const profile of playerClients) {
      let p: PlayerResponse;
      try {
        p = await this.client.callJSON<PlayerResponse>(
          "player",
          profile,
          { videoId, contentCheckOk: true, racyCheckOk: true },
          { signal },
        );
      } catch (err) {
        attempts.push(profile.name + ": " + errorText(err));
        continue;
      }
      if (p.playabilityStatus?.status === "OK" && p.videoDetails?.videoId) {
        return { player: p, clientName: profile.name };
      }
      const reason =
        p.playabilityStatus?.reason ??
        p.playabilityStatus?.errorScreen?.playerErrorMessageRenderer?.reason?.simpleText ??
        "";
      attempts.push(`${profile.name}: ${p.playabilityStatus?.status ?? ""} (${reason})`);
    }
    throw classifyPlayabilityFailure(videoId, attempts);
  }

  /** Calls the player endpoint with a single client identity. */
  async fetchPlayerWith(
    videoId: string,
    profile: InnertubeProfile,
    signal?: AbortSignal,
  ): Promise<PlayerResponse> {
    return this.client.callJSON<PlayerResponse>(
      "player",
      profile,
      { videoId, contentCheckOk: true, racyCheckOk: true },
      { signal },
    );
  }

  // ------------------------------------------------------------------ info

  /** Normalized metadata for one video. */
  async info(input: string, signal?: AbortSignal): Promise<VideoInfo> {
    const id = parseVideoId(input);
    const cached = await this.client.cache.get<VideoInfo>("info", id);
    if (cached !== undefined) {
      return cached;
    }
    const { player } = await this.fetchPlayer(id, signal);
    const info = infoFromPlayer(id, player);
    await this.enrichMicroformat(id, info, signal);
    await this.client.cache.set("info", id, info);
    return info;
  }

  /**
   * Fills in the fields only the WEB player reports (category, publish/upload
   * date, likes, embed, availability). The mobile clients preferred for
   * playable streams omit the microformat block entirely. Best-effort: any
   * failure just leaves the extra fields empty.
   */
  async enrichMicroformat(id: string, info: VideoInfo, signal?: AbortSignal): Promise<void> {
    if (info.category && info.publishDate && (info.likeCount ?? 0) > 0) {
      return;
    }
    if (process.env.YTUBE_RICH_METADATA === "0") {
      return;
    }
    let p: PlayerResponse;
    try {
      p = await this.client.callJSON<PlayerResponse>(
        "player",
        clientWEB,
        { videoId: id, contentCheckOk: true, racyCheckOk: true },
        { signal },
      );
    } catch {
      return;
    }
    const micro = p.microformat?.playerMicroformatRenderer ?? {};
    if (!info.publishDate) {
      info.publishDate = micro.publishDate || undefined;
    }
    if (!info.uploadDate) {
      info.uploadDate = micro.uploadDate || undefined;
    }
    if (!info.category) {
      info.category = micro.category || undefined;
    }
    if (!info.likeCount) {
      info.likeCount = parseIntOr0(micro.likeCount) || undefined;
    }
    if (!info.embedUrl) {
      info.embedUrl = micro.embed?.iframeUrl || undefined;
    }
    if (micro.ownerProfileUrl) {
      info.channelUrl = micro.ownerProfileUrl;
    }
    if (!info.availableCountryCount) {
      info.availableCountryCount = micro.availableCountries?.length || undefined;
    }
    info.isFamilySafe = info.isFamilySafe || micro.isFamilySafe === true;
    info.isUnlisted = info.isUnlisted === true || micro.isUnlisted === true ? true : undefined;
  }

  // -------------------------------------------------------------- captions

  /** Lists available caption tracks for a video (no signed URLs). */
  async listCaptions(input: string, signal?: AbortSignal): Promise<CaptionTrackSummary[]> {
    const id = parseVideoId(input);
    const resolved = await this.resolveCaptionTracks(id, signal);
    return resolved.tracks.map(toCaptionTrackSummary);
  }

  /**
   * Walks ANDROID → IOS → WEB until usable caption tracks appear. Tracks from
   * later clients are merged in, keyed by (language, kind), so each track
   * carries alternate baseUrls for empty-body escalation.
   */
  async resolveCaptionTracks(videoId: string, signal?: AbortSignal): Promise<ResolvedCaptions> {
    const result = await this.resolveCaptionTracksResult(videoId, signal);
    if (result.error !== undefined) {
      throw result.error;
    }
    return { tracks: result.tracks, attempts: result.attempts, clients: result.clients };
  }

  /** `resolveCaptionTracks` that reports failure instead of throwing. */
  async resolveCaptionTracksResult(
    videoId: string,
    signal?: AbortSignal,
  ): Promise<ResolvedCaptionsResult> {
    const out: ResolvedCaptionsResult = { tracks: [], attempts: [], clients: [] };
    const byKey = new Map<string, number>();

    for (const profile of captionClients) {
      let p: PlayerResponse;
      try {
        p = await this.fetchPlayerWith(videoId, profile, signal);
      } catch (err) {
        out.attempts.push(profile.name + ": " + errorText(err));
        continue;
      }
      const status = p.playabilityStatus?.status ?? "";
      const tracks = captionsFromPlayer(p);
      if (status !== "OK" && tracks.length === 0) {
        const reason =
          p.playabilityStatus?.reason ??
          p.playabilityStatus?.errorScreen?.playerErrorMessageRenderer?.reason?.simpleText ??
          "";
        out.attempts.push(`${profile.name}: ${status} (${reason})`);
        continue;
      }
      out.attempts.push(`${profile.name}: ${status} tracks=${tracks.length}`);
      if (tracks.length === 0) {
        continue;
      }
      out.clients.push(profile.name);
      for (const t of tracks) {
        const kind = t.isAutoGenerated ? "asr" : "manual";
        const key = t.languageCode.toLowerCase() + "|" + kind;
        const idx = byKey.get(key);
        if (idx !== undefined) {
          const existing = out.tracks[idx]!;
          existing.altUrls = appendUniqueUrl(trackAltUrls(existing), trackBaseUrl(t));
          if (t.isTranslatable) {
            existing.isTranslatable = true;
          }
          continue;
        }
        byKey.set(key, out.tracks.length);
        out.tracks.push({ ...t, sourceClient: profile.name });
      }
      // Common case: first client already gave us tracks. Keep probing only when
      // YTUBE_CAPTION_ALL_CLIENTS=1 asks for full diagnostics.
      if (out.tracks.length > 0 && process.env.YTUBE_CAPTION_ALL_CLIENTS !== "1") {
        return out;
      }
    }

    if (out.tracks.length === 0) {
      out.error = new ExtractError({
        code: "NO_CAPTIONS",
        message:
          "This video has no caption tracks (the uploader disabled them or YouTube has not generated any)",
        details: { attempts: out.attempts },
      });
    }
    return out;
  }

  // ------------------------------------------------------------ transcript

  /**
   * Downloads and parses the caption track for lang ("" = best).
   * Auto-generated tracks are sentence-merged by default.
   */
  async transcript(input: string, lang?: string, signal?: AbortSignal): Promise<Transcript> {
    return this.transcriptWithOptions(input, { lang }, signal);
  }

  /** `transcript` with explicit merge/language controls. */
  async transcriptWithOptions(
    input: string,
    opts: TranscriptOptions,
    signal?: AbortSignal,
  ): Promise<Transcript> {
    const id = parseVideoId(input);
    const cacheKey = transcriptCacheKey(id, opts);
    const cached = await this.client.cache.get<Transcript>("transcript", cacheKey);
    if (cached !== undefined) {
      return cached;
    }

    // If timedtext is cooling down after a 429, skip the live round-trip and
    // serve stale cache immediately — that is what stops IP bans from cascading.
    if (isTimedtextCoolingDown()) {
      const stale = await this.client.cache.getStale<Transcript>("transcript", cacheKey);
      if (stale !== undefined) {
        return annotateStale(stale, "timedtext cooldown after HTTP 429");
      }
      // Best-effort: any cached language for this video (lang-chain / alt opts).
      for (const altLang of [...parseLangChain(opts.lang), "", "en"]) {
        const altKey = transcriptCacheKey(id, { ...opts, lang: altLang || undefined });
        if (altKey === cacheKey) continue;
        const alt = await this.client.cache.getStale<Transcript>("transcript", altKey);
        if (alt !== undefined) {
          const tr = annotateStale(alt, `timedtext cooldown; served cached lang "${alt.value.languageCode}"`);
          tr.requestedLang = opts.lang || tr.requestedLang;
          return tr;
        }
      }
    }

    let result: Transcript;
    try {
      result = await this.fetchTranscriptLive(id, opts, signal);
    } catch (fetchErr) {
      if (isRetryableExtract(fetchErr)) {
        const stale = await this.client.cache.getStale<Transcript>("transcript", cacheKey);
        if (stale !== undefined) {
          return annotateStale(stale, `live fetch failed: ${errorText(fetchErr)}`);
        }
        for (const altLang of [...parseLangChain(opts.lang), "", "en"]) {
          const altKey = transcriptCacheKey(id, { ...opts, lang: altLang || undefined });
          if (altKey === cacheKey) continue;
          const alt = await this.client.cache.getStale<Transcript>("transcript", altKey);
          if (alt !== undefined) {
            const tr = annotateStale(alt, `live fetch failed; served cached lang "${alt.value.languageCode}"`);
            tr.requestedLang = opts.lang || tr.requestedLang;
            return tr;
          }
        }
      }
      throw fetchErr;
    }
    await this.client.cache.set("transcript", cacheKey, result);
    return result;
  }

  /** Transcript plus a bounded page window (`paging.ts`). */
  async transcriptPage(
    input: string,
    opts: TranscriptOptions,
    cursor: number,
    maxChars: number,
    signal?: AbortSignal,
  ): Promise<TranscriptPage> {
    const transcript = await this.transcriptWithOptions(input, opts, signal);
    return pageTranscript(transcript, cursor, maxChars);
  }

  private async fetchTranscriptLive(
    id: string,
    opts: TranscriptOptions,
    signal?: AbortSignal,
  ): Promise<Transcript> {
    const resolved = await this.resolveCaptionTracks(id, signal);
    const tracks = resolved.tracks;

    if (opts.translateTo) {
      // Force translate path: pick any translatable base and set tlang.
      const base = pickCaptionTrack(tracks, "", true);
      if (!base.track.isTranslatable) {
        throw new ExtractError({
          code: "TRANSLATION_UNAVAILABLE",
          message: "No translatable caption track available for this video",
        });
      }
      const url = withTranscriptLang(trackBaseUrl(base.track), opts.translateTo);
      const picked: PickCaptionResult = {
        track: {
          languageCode: opts.translateTo,
          name: base.track.name,
          isAutoGenerated: true,
          isTranslatable: true,
          baseUrl: url,
          altUrls: altTranslateUrls(base.track, opts.translateTo),
          sourceClient: base.track.sourceClient,
        },
        captionUrl: url,
        translatedFrom: base.track.languageCode,
        source: "translated",
        resolvedLang: opts.translateTo,
        warnings: [],
      };
      return this.materializeTranscript(id, picked, opts, resolved.attempts, signal);
    }

    let picked: PickCaptionResult;
    try {
      picked = pickCaptionTrack(tracks, opts.lang, opts.strict === true);
    } catch (err) {
      if (isExtractError(err)) {
        err.details = mergeDetails(err.details, { attempts: resolved.attempts });
      }
      throw err;
    }
    return this.materializeTranscript(id, picked, opts, resolved.attempts, signal);
  }

  private async materializeTranscript(
    id: string,
    picked: PickCaptionResult,
    opts: TranscriptOptions,
    attempts: string[],
    signal?: AbortSignal,
  ): Promise<Transcript> {
    const capKey = captionsCacheKey(
      id,
      picked.resolvedLang,
      picked.track.isAutoGenerated,
      picked.translatedFrom,
      opts.words === true,
    );
    let rawSegs = await this.client.cache.get<TranscriptSegment[]>("captions", capKey);
    if (rawSegs === undefined) {
      rawSegs = await this.fetchCaptionSegmentsEscalated(id, picked, opts.words === true, signal);
      if (rawSegs.length === 0) {
        let code = "EMPTY_TRANSCRIPT";
        let msg =
          "YouTube returned an empty caption body; the track may be PO-token gated on this client. Retry, set YTUBE_PO_TOKEN, or try another language.";
        if (picked.translatedFrom !== "") {
          code = "TRANSLATION_UNAVAILABLE";
          msg = `YouTube returned an empty auto-translation to "${picked.resolvedLang}" from "${picked.translatedFrom}"`;
        }
        throw new ExtractError({
          code,
          message: msg,
          retryable: true,
          details: { attempts },
        });
      }
      await this.client.cache.set("captions", capKey, rawSegs);
    }

    let segments = rawSegs;
    if (opts.stripSoundTags === true) {
      segments = stripSoundTagSegments(segments);
    }
    if (opts.words !== true) {
      segments = segments.map((s) => ({ ...s, words: undefined }));
    }

    const merge = shouldMerge(
      opts,
      picked.track.isAutoGenerated || picked.translatedFrom !== "",
    );
    const result = buildTranscript(
      id,
      picked.track,
      segments,
      merge,
      picked.translatedFrom,
      picked.source,
      opts.lang ?? "",
      [...picked.warnings],
    );
    if (process.env.YTUBE_DEBUG === "1") {
      result.attempts = attempts;
    }
    if (opts.groupByChapters === true) {
      try {
        const chaps = await chaptersFor(this, id, signal);
        if (chaps.chapters.length > 0) {
          result.chapters = groupSegmentsByChapters(id, result.segments, chaps.chapters);
        }
      } catch {
        // Chapters are decoration; a failure must not fail the transcript.
      }
    }
    return result;
  }

  // ----------------------------------------------------------- caption I/O

  /**
   * Tries the primary URL, then alternate client signatures, then a fresh
   * player signature, then a PO-token URL.
   */
  async fetchCaptionSegmentsEscalated(
    videoId: string,
    picked: PickCaptionResult,
    wantWords: boolean,
    signal?: AbortSignal,
  ): Promise<TranscriptSegment[]> {
    const urls = [picked.captionUrl, ...trackAltUrls(picked.track)];
    const pot = withPOToken(picked.captionUrl);
    if (pot !== picked.captionUrl) {
      urls.push(pot);
    }

    let lastErr: unknown = null;
    for (const u of urls) {
      try {
        const segs = await this.fetchCaptionSegments(u, wantWords, signal);
        if (segs.length > 0) {
          return segs;
        }
      } catch (err) {
        lastErr = err;
        if (isExtractError(err) && err.code === "RATE_LIMITED") {
          throw err;
        }
      }
    }

    // Fresh signature from an alternate client (skip when already rate-limited).
    if (isExtractError(lastErr) && lastErr.code === "RATE_LIMITED") {
      throw lastErr;
    }
    for (const profile of [clientIOS, clientANDROID]) {
      let p: PlayerResponse;
      try {
        p = await this.fetchPlayerWith(videoId, profile, signal);
      } catch (err) {
        lastErr = err;
        continue;
      }
      const fresh = captionsFromPlayer(p);
      let match: CaptionTrack | null = null;
      for (const track of fresh) {
        if (
          track.languageCode.toLowerCase() === picked.track.languageCode.toLowerCase() &&
          track.isAutoGenerated === picked.track.isAutoGenerated
        ) {
          match = track;
          break;
        }
      }
      if (match === null && fresh.length > 0) {
        match = fresh[0]!;
      }
      if (match === null) {
        continue;
      }
      let u = trackBaseUrl(match);
      if (picked.translatedFrom !== "") {
        u = withTranscriptLang(u, picked.resolvedLang);
      }
      try {
        const segs = await this.fetchCaptionSegments(u, wantWords, signal);
        if (segs.length > 0) {
          return segs;
        }
      } catch (err) {
        lastErr = err;
        continue;
      }
      const potUrl = withPOToken(u);
      if (potUrl !== u) {
        try {
          const segs = await this.fetchCaptionSegments(potUrl, wantWords, signal);
          if (segs.length > 0) {
            return segs;
          }
        } catch (err) {
          lastErr = err;
        }
      }
    }

    if (lastErr !== null) {
      throw lastErr;
    }
    return [];
  }

  /**
   * Downloads a caption track, trying json3 first and falling back to the
   * srv1/srv3 XML formats.
   */
  async fetchCaptionSegments(
    baseUrl: string,
    wantWords: boolean,
    signal?: AbortSignal,
  ): Promise<TranscriptSegment[]> {
    let json3Err: unknown = null;
    try {
      const segs = await this.fetchJSON3(withFormat(baseUrl, "json3"), wantWords, signal);
      if (segs.length > 0) {
        return segs;
      }
    } catch (err) {
      if (isExtractError(err) && err.code === "RATE_LIMITED") {
        throw err;
      }
      json3Err = err;
    }
    // Prefer classic srv1 <transcript>; also try srv3 <timedtext>.
    for (const format of ["srv1", "srv3"]) {
      try {
        const segs = await this.fetchTimedTextXML(withFormat(baseUrl, format), signal);
        if (segs.length > 0) {
          return segs;
        }
      } catch (err) {
        if (isExtractError(err) && err.code === "RATE_LIMITED") {
          throw err;
        }
      }
    }
    if (json3Err !== null) {
      throw json3Err;
    }
    return this.fetchTimedTextXML(baseUrl, signal);
  }

  /**
   * Plain GET for a timedtext URL. Uses a browser UA + Referer (matches how the
   * watch page loads captions) and carries the cookie jar when present.
   */
  private async captionFetch(
    url: string,
    signal?: AbortSignal,
  ): Promise<{ status: number; body: string; retryAfterSec?: number }> {
    assertTimedtextAllowed();
    const headers: Record<string, string> = {
      "User-Agent": WEB_USER_AGENT,
      Accept: "*/*",
      "Accept-Language": "en-US,en;q=0.9",
      Origin: "https://www.youtube.com",
      Referer: "https://www.youtube.com/",
    };
    const cookie = this.client.cookieHeader(url);
    if (cookie !== "") {
      headers["Cookie"] = cookie;
    }
    const timeout = AbortSignal.timeout(this.client.timeoutMs);
    const response = await fetch(url, {
      headers,
      signal: anySignal(timeout, signal),
      redirect: "follow",
    });
    const retryAfterRaw = response.headers.get("retry-after");
    let retryAfterSec: number | undefined;
    if (retryAfterRaw) {
      const n = Number.parseInt(retryAfterRaw, 10);
      if (Number.isFinite(n) && n > 0) retryAfterSec = n;
    }
    return { status: response.status, body: await response.text(), retryAfterSec };
  }

  /** GET a caption body; first 429 arms the cooldown and stops further GETs. */
  async captionGet(u: string, signal?: AbortSignal): Promise<string> {
    assertTimedtextAllowed();
    let lastErr: unknown = null;
    // At most 2 attempts per URL — long backoff. Escalation tries other signatures.
    for (let attempt = 0; attempt < Math.min(MAX_RETRIES, 2); attempt++) {
      if (attempt > 0) {
        const backoff = 1000 * (1 << attempt); // 2s, 4s…
        try {
          await sleep(backoff, undefined, { signal });
        } catch (err) {
          throw classifyNetworkError(err);
        }
      }
      let response: { status: number; body: string; retryAfterSec?: number };
      try {
        response = await this.captionFetch(u, signal);
      } catch (err) {
        if (isExtractError(err) && err.code === "RATE_LIMITED") throw err;
        lastErr = classifyNetworkError(err);
        continue;
      }
      if (response.status === 429) {
        markTimedtextRateLimited(response.retryAfterSec);
        throw httpStatusError(response.status);
      }
      if (response.status >= 500) {
        lastErr = httpStatusError(response.status);
        continue;
      }
      if (response.status !== 200) {
        throw httpStatusError(response.status);
      }
      if (response.body.length === 0) {
        throw new ExtractError({
          code: "EMPTY_TRANSCRIPT",
          message: "YouTube returned an empty caption body",
          retryable: true,
        });
      }
      return response.body;
    }
    throw (
      lastErr ??
      new ExtractError({
        code: "RATE_LIMITED",
        message: "Caption download failed after retries",
        retryable: true,
      })
    );
  }

  /** Parses the json3 caption format, optionally keeping word-level offsets. */
  async fetchJSON3(
    u: string,
    wantWords: boolean,
    signal?: AbortSignal,
  ): Promise<TranscriptSegment[]> {
    const data = await this.captionGet(u, signal);
    let body: Json3Body;
    try {
      body = JSON.parse(data) as Json3Body;
    } catch (err) {
      throw new Error(`json3 parse failed: ${(err as Error).message}`);
    }
    const segments: TranscriptSegment[] = [];
    for (const ev of body.events ?? []) {
      if (isAppendEvent(ev.aAppend) || (ev.segs ?? []).length === 0) {
        continue;
      }
      const start = ev.tStartMs ?? 0;
      let raw = "";
      const words: TranscriptWord[] = [];
      for (const s of ev.segs ?? []) {
        const utf8 = s.utf8 ?? "";
        raw += utf8;
        if (wantWords) {
          const w = utf8.trim();
          if (w === "" || w === "\n") {
            continue;
          }
          words.push({
            text: w,
            start: (start + (s.tOffsetMs ?? 0)) / 1000,
            timestamp: "",
          });
        }
      }
      const text = normalizeCaptionText(raw);
      if (text === "") {
        continue;
      }
      segments.push({
        text,
        start: start / 1000,
        duration: (ev.dDurationMs ?? 0) / 1000,
        end: 0,
        timestamp: "",
        timestampEnd: "",
        words: words.length > 0 ? words : undefined,
      });
    }
    return segments;
  }

  /** Downloads and parses srv1 (`<transcript>`) or srv3 (`<timedtext>`) caption XML. */
  async fetchTimedTextXML(baseUrl: string, signal?: AbortSignal): Promise<TranscriptSegment[]> {
    const raw = await this.captionGet(baseUrl, signal);
    if (raw.length === 0) {
      return [];
    }
    return parseTimedTextXML(raw);
  }

  // ------------------------------------------------------- module facades

  /** Chapter markers for a video (`chapters.ts`). */
  async chapters(input: string, signal?: AbortSignal): Promise<ChaptersResult> {
    return chaptersFor(this, input, signal);
  }

  /** Transcript restricted to [start, end] seconds (`subtitles.ts`). */
  async transcriptClip(
    input: string,
    lang: string | undefined,
    start: number,
    end: number,
    signal?: AbortSignal,
  ): Promise<Transcript> {
    return transcriptClip(this, input, lang, start, end, signal);
  }

  /** Case-insensitive transcript search (`subtitles.ts`). */
  async searchTranscript(
    input: string,
    lang: string | undefined,
    query: string,
    contextWindow: number,
    signal?: AbortSignal,
  ): Promise<TranscriptSearchResult> {
    return searchTranscript(this, input, lang, query, contextWindow, signal);
  }

  /** Captions rendered as srt/vtt/ass/json/text/chapters (`subtitles.ts`). */
  async exportSubtitles(
    input: string,
    lang: string | undefined,
    format: string,
    outPath: string,
    signal?: AbortSignal,
  ): Promise<SubtitleExport> {
    return exportSubtitles(this, input, lang, format, outPath, signal);
  }

  /** Stream formats for a video (`media.ts`). */
  async formats(input: string, signal?: AbortSignal): Promise<FormatsResult> {
    return listFormats(this, input, signal);
  }

  /** Downloads one direct-URL format to disk (`media.ts`). */
  async download(
    input: string,
    itag: number,
    outPath: string,
    signal?: AbortSignal,
  ): Promise<DownloadResult> {
    return downloadMedia(this, input, itag, outPath, signal);
  }

  /** Per-stage report of the caption resolution ladder (`diagnose.ts`). */
  async diagnoseTranscript(
    input: string,
    lang?: string,
    signal?: AbortSignal,
  ): Promise<TranscriptDiagnosis> {
    return diagnoseTranscript(this, input, lang, signal);
  }

  /** Every thumbnail rendition for a video, keyed like the Go CLI payload. */
  async thumbnails(
    input: string,
    signal?: AbortSignal,
  ): Promise<{ videoId: string; thumbnails: Thumbnail[] }> {
    const info = await this.info(input, signal);
    return { videoId: info.id, thumbnails: info.thumbnails };
  }

  /** Citation-ready RAG/briefing pack for one video (`rag.ts`). */
  async videoPack(
    input: string,
    opts: PackOptions = {},
    signal?: AbortSignal,
  ): Promise<VideoPack> {
    return videoPackFor(this, input, opts, signal);
  }

  /** Transcript passages most relevant to a question (`ask.ts`). */
  async askVideo(
    input: string,
    question: string,
    opts: AskOptions = {},
    signal?: AbortSignal,
  ): Promise<AskResult> {
    return askVideoFor(this, input, question, opts, signal);
  }

  /** Packs for a playlist, channel, or explicit video list (`batch.ts`). */
  async batchPack(
    input: string,
    opts: BatchOptions = {},
    signal?: AbortSignal,
  ): Promise<BatchPack> {
    return batchPackFor(this, input, opts, signal);
  }

  /** Comment threads with paging and reply expansion (`comments.ts`). */
  async comments(
    input: string,
    opts: CommentsOptions = {},
    signal?: AbortSignal,
  ): Promise<CommentsResult> {
    return commentsFor(this, input, opts, signal);
  }

  /** Playlist metadata and items (`discovery.ts`). */
  async playlist(input: string, limit = 0, signal?: AbortSignal): Promise<PlaylistResult> {
    return playlistFor(this, input, limit, signal);
  }

  /** Channel metadata and recent videos over InnerTube (`discovery.ts`). */
  async channel(input: string, limit = 0, signal?: AbortSignal): Promise<ChannelResult> {
    return channelFor(this, input, limit, signal);
  }

  /** Channel lookup preferring the Data API when a key is set (`dataapi.ts`). */
  async channelPreferAPI(
    input: string,
    limit = 0,
    signal?: AbortSignal,
  ): Promise<ChannelPreferResult> {
    return channelPreferAPIFor(this, input, limit, signal);
  }

  /** InnerTube search (`discovery.ts`). */
  async search(query: string, limit = 0, signal?: AbortSignal): Promise<SearchResults> {
    return searchFor(this, query, limit, signal);
  }

  /** Search preferring the Data API when a key is set (`dataapi.ts`). */
  async searchPreferAPI(
    query: string,
    limit = 0,
    signal?: AbortSignal,
  ): Promise<SearchPreferResult> {
    return searchPreferAPIFor(this, query, limit, signal);
  }

  /** Opt-in SponsorBlock skip ranges (`sponsorblock.ts`). */
  async sponsorSegments(input: string, signal?: AbortSignal): Promise<SponsorSegment[]> {
    return sponsorSegmentsFor(this, input, signal);
  }

  /** Videos suggested alongside this one (`extras.ts`). */
  async related(input: string, signal?: AbortSignal): Promise<RelatedResultWithCache> {
    return relatedFor(this, input, signal);
  }

  /** Most-replayed intensity markers (`extras.ts`). */
  async heatmap(input: string, signal?: AbortSignal): Promise<HeatmapResult> {
    return heatmapFor(this, input, signal);
  }

  /** Storyboard (scrubbing preview) tile URLs (`extras.ts`). */
  async storyboards(input: string, signal?: AbortSignal): Promise<StoryboardsResult> {
    return storyboardsFor(this, input, signal);
  }

  /** DASH/HLS manifest URLs and live status (`extras.ts`). */
  async manifests(input: string, signal?: AbortSignal): Promise<ManifestsResult> {
    return manifestsFor(this, input, signal);
  }
}

/** Builds an `Engine` around an existing InnerTube client. */
export function createEngine(client: Client): Engine {
  return new Engine(client);
}

/** Rewrites (or appends) the `fmt=` parameter of a timedtext URL. */
export function withFormat(baseUrl: string, format: string): string {
  if (FMT_PARAM_PATTERN.test(baseUrl)) {
    return baseUrl.replace(new RegExp(FMT_PARAM_PATTERN.source, "g"), "fmt=" + format);
  }
  return baseUrl + "&fmt=" + format;
}

/**
 * Parses srv1/srv3 timedtext XML without a DOM. YouTube's caption XML is flat
 * and machine-generated, so a scanning parser matches Go's `encoding/xml`
 * results for every shape the API emits.
 */
export function parseTimedTextXML(raw: string): TranscriptSegment[] {
  if (raw.includes("<transcript")) {
    const segments: TranscriptSegment[] = [];
    const pattern = /<text\b([^>]*?)(\/>|>([\s\S]*?)<\/text\s*>)/g;
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(raw)) !== null) {
      const attrs = match[1] ?? "";
      const body = match[3] ?? "";
      const text = normalizeCaptionText(decodeCaptionBody(body));
      if (text === "") {
        continue;
      }
      segments.push({
        text,
        start: attrFloat(attrs, "start"),
        duration: attrFloat(attrs, "dur"),
        end: 0,
        timestamp: "",
        timestampEnd: "",
      });
    }
    return segments;
  }

  if (raw.includes("<timedtext")) {
    const bodyMatch = /<body\b[^>]*>([\s\S]*?)<\/body\s*>/.exec(raw);
    const bodyXml = bodyMatch?.[1] ?? "";
    const segments: TranscriptSegment[] = [];
    const pattern = /<p\b([^>]*?)(\/>|>([\s\S]*?)<\/p\s*>)/g;
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(bodyXml)) !== null) {
      const attrs = match[1] ?? "";
      const inner = match[3] ?? "";
      // Go collects the paragraph's own chardata first, then each <s> span.
      const spans: string[] = [];
      const spanPattern = /<s\b[^>]*?(?:\/>|>([\s\S]*?)<\/s\s*>)/g;
      let spanMatch: RegExpExecArray | null;
      while ((spanMatch = spanPattern.exec(inner)) !== null) {
        spans.push(spanMatch[1] ?? "");
      }
      const ownText = inner.replace(spanPattern, "").replace(/<[^>]*>/g, "");
      const text = normalizeCaptionText(decodeCaptionBody(ownText + spans.join("")));
      if (text === "") {
        continue;
      }
      segments.push({
        text,
        start: attrFloat(attrs, "t") / 1000,
        duration: attrFloat(attrs, "d") / 1000,
        end: 0,
        timestamp: "",
        timestampEnd: "",
      });
    }
    return segments;
  }

  throw new ExtractError({
    code: "CAPTION_PARSE_ERROR",
    message: "YouTube returned an unrecognized caption format",
    retryable: true,
    details: { head: raw.slice(0, Math.min(120, raw.length)) },
  });
}
