/**
 * Public data model of the extraction engine.
 *
 * Field names and optionality mirror the JSON tags of the Go structs in
 * internal/youtube so that payloads produced by either implementation are
 * interchangeable.
 */

export type SubtitleFormat = "srt" | "vtt" | "ass" | "json" | "text" | "chapters";
export type CommentSort = "top" | "newest";

/**
 * Enum-ish values the engine reports. The Go structs type these fields as plain
 * `string`, so the `(string & {})` member keeps any string assignable while
 * editors still suggest the values the engine actually emits.
 */
export type TranscriptSource = "manual" | "asr" | "translated" | "fallback" | (string & {});
export type ChapterSource = "markers" | "description" | "none" | (string & {});
export type BatchSourceKind = "playlist" | "channel" | "videos" | (string & {});
export type BatchDetail = "summary" | "analysis";
export type SearchResultKind = "video" | "channel" | "playlist" | (string & {});

export interface Thumbnail {
  url: string;
  width?: number;
  height?: number;
}

export interface VideoInfo {
  id: string;
  url: string;
  title: string;
  description: string;
  channelId: string;
  channelName: string;
  channelUrl?: string;
  durationSeconds: number;
  duration?: string;
  viewCount?: number;
  likeCount?: number;
  publishDate?: string;
  uploadDate?: string;
  category?: string;
  keywords?: string[];
  isLive: boolean;
  isUnlisted?: boolean;
  isFamilySafe: boolean;
  availableCountryCount?: number;
  embedUrl?: string;
  thumbnails: Thumbnail[];
}

export interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
  sourceClient?: string;
  /** Not serialized: timedtext endpoint for this track. */
  baseUrl: string;
  /** Not serialized: alternate client signatures used for empty-body retries. */
  altUrls: string[];
}

export interface TranscriptWord {
  text: string;
  start: number;
  duration?: number;
  timestamp: string;
}

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
  end: number;
  timestamp: string;
  timestampEnd: string;
  words?: TranscriptWord[];
}

export interface Chapter {
  title: string;
  startSeconds: number;
  timestamp: string;
}

export interface ChapterGroup {
  title: string;
  startSeconds: number;
  timestamp: string;
  url: string;
  segments: TranscriptSegment[];
  text: string;
}

export interface Transcript {
  videoId: string;
  languageCode: string;
  languageName: string;
  requestedLang?: string;
  resolvedLang?: string;
  source?: TranscriptSource;
  isAutoGenerated: boolean;
  translatedFrom?: string;
  merged: boolean;
  rawSegmentCount: number;
  segmentCount: number;
  durationSeconds: number;
  segments: TranscriptSegment[];
  lines: string[];
  text: string;
  warnings?: string[];
  stale?: boolean;
  staleAgeSeconds?: number;
  attempts?: string[];
  chapters?: ChapterGroup[];
}

/** A bounded window over a transcript; follow `nextCursor` until `hasMore` is false. */
export interface TranscriptPage extends Transcript {
  cursor: number;
  nextCursor?: number;
  hasMore: boolean;
  totalSegments: number;
  totalChars: number;
  pageChars: number;
}

export interface ChaptersResult {
  videoId: string;
  title: string;
  chapters: Chapter[];
  count: number;
  hasChapters: boolean;
  source: ChapterSource;
}

export interface Format {
  itag: number;
  mimeType: string;
  quality?: string;
  qualityLabel?: string;
  audioQuality?: string;
  bitrate?: number;
  contentLength?: number;
  hasAudio: boolean;
  hasVideo: boolean;
  directUrl: boolean;
  /** Not serialized: resolved media URL. */
  streamUrl?: string;
}

export interface DownloadResult {
  path: string;
  itag: number;
  mimeType: string;
  bytesWritten: number;
}

/** One citation-sized window of transcript text. */
export interface RAGChunk {
  id: string;
  text: string;
  /** Human-facing citation marker, e.g. `[1:07:12]`. */
  citation: string;
  /** Deep link that opens the video at `start`. */
  url: string;
  start: number;
  end: number;
  timestamp: string;
  timestampEnd: string;
  charCount: number;
}

export interface SponsorSegment {
  category: string;
  start: number;
  end: number;
  timestamp: string;
  timestampEnd: string;
}

/** Agent-ready briefing for a single video. */
export interface VideoPack {
  video: VideoInfo | null;
  chapters: Chapter[];
  chapterSource: string;
  language: string;
  mergedAsr: boolean;
  chunkCount: number;
  chunks: RAGChunk[];
  markdown: string;
  howToCite: string;
  sponsorSegments?: SponsorSegment[];
  removedSeconds?: number;
  cacheHit?: boolean;
}

export interface Passage {
  chunk: RAGChunk;
  score: number;
}

export interface AskResult {
  videoId: string;
  title: string;
  url: string;
  question: string;
  language?: string;
  matched: number;
  passages: Passage[];
  context: string;
  howToCite: string;
}

export interface BatchItem {
  videoId: string;
  title: string;
  url: string;
  durationSeconds: number;
  /** Channel-tab provenance when the source is a creator channel. */
  contentType?: ChannelItemContentType;
  language?: string;
  chunkCount: number;
  chunks?: RAGChunk[];
  /** Present when `detail: "analysis"` is requested. */
  video?: VideoInfo;
  /** Present when `detail: "analysis"` is requested. */
  transcript?: Transcript;
  /** Present when `detail: "analysis"` is requested. */
  chapters?: Chapter[];
  chapterSource?: string;
  cacheHit?: boolean;
}

export interface BatchFailure {
  videoId: string;
  title?: string;
  contentType?: ChannelItemContentType;
  code: string;
  message: string;
  retryable: boolean;
}

export interface BatchPack {
  source: BatchSourceKind;
  sourceId?: string;
  title?: string;
  totalVideos: number;
  /** False means `totalVideos` is the count discovered so far, not the final total. */
  catalogComplete?: boolean;
  discoveredVideos?: number;
  videoCount?: number;
  shortCount?: number;
  cursor: number;
  nextCursor?: number;
  hasMore: boolean;
  videos: BatchItem[];
  failures?: BatchFailure[];
  totalChunks: number;
  markdown: string;
  howToCite: string;
}

export interface Comment {
  id?: string;
  author: string;
  text: string;
  likeCount?: string;
  published?: string;
  isPinned: boolean;
  replyCount?: number;
  replies?: Comment[];
}

export interface CommentsResult {
  videoId: string;
  comments: Comment[];
  count: number;
  sort: string;
  nextCursor?: string;
  hasMore?: boolean;
  note?: string;
}

export interface PlaylistItem {
  id: string;
  title: string;
  channelName?: string;
  index: number;
  lengthText?: string;
}

export interface PlaylistResult {
  id: string;
  title: string;
  owner: string;
  items: PlaylistItem[];
  count: number;
}

export interface ChannelVideo {
  id: string;
  title: string;
  lengthText?: string;
}

export interface ChannelResult {
  id: string;
  handle: string;
  title: string;
  description: string;
  subscribers: string;
  videos: ChannelVideo[];
  count: number;
}

/** Provenance of a catalog entry: which channel tab produced it. */
export type ChannelItemContentType = "video" | "short";

/** Filter controlling which channel tabs `discoverChannelCatalog` advances. */
export type ChannelCatalogContentFilter = "all" | "videos" | "shorts" | (string & {});

/** One discovered upload or Short from a creator channel. */
export interface ChannelCatalogItem {
  id: string;
  title: string;
  contentType: ChannelItemContentType;
  lengthText?: string;
}

/** Progressive Videos/Shorts discovery result for a creator channel. */
export interface ChannelCatalog {
  id: string;
  handle: string;
  title: string;
  description: string;
  subscribers: string;
  items: ChannelCatalogItem[];
  count: number;
  videoCount: number;
  shortCount: number;
  /** True when every requested tab has been exhausted (or was unavailable). */
  complete: boolean;
}

/** Bounded page over a progressively discovered creator catalog. */
export interface ChannelCatalogPage extends Omit<ChannelCatalog, "items"> {
  items: ChannelCatalogItem[];
  cursor: number;
  nextCursor?: number;
  hasMore: boolean;
  discoveredVideos: number;
}

/** Options for progressive / exhaustive channel catalog discovery. */
export interface ChannelCatalogOptions {
  /** Which tabs to include; defaults to `"all"`. */
  contentType?: ChannelCatalogContentFilter;
  /**
   * Minimum items to discover before returning. `0` (default) means follow
   * continuations until every requested tab is complete.
   */
  ensure?: number;
  /** Start a new snapshot. Invalidates cursors from the previous snapshot. */
  refresh?: boolean;
}

export interface ChannelCatalogPageOptions {
  contentType?: ChannelCatalogContentFilter;
  limit?: number;
  cursor?: number;
  refresh?: boolean;
}

export type ChannelExportStatus = "running" | "paused" | "completed";

/** Options for a checkpointed full-channel JSONL analysis export. */
export interface ChannelExportOptions extends PackOptions {
  contentType?: ChannelCatalogContentFilter;
  /** Resume a prior deterministic export. Usually copied from a previous result. */
  jobId?: string;
}

/** Summary returned by the checkpointed channel export operation. */
export interface ChannelExportResult {
  jobId: string;
  channelId: string;
  title: string;
  status: ChannelExportStatus;
  dataPath: string;
  checkpointPath: string;
  catalogVideos: number;
  cursor: number;
  nextCursor?: number;
  succeeded: number;
  failed: number;
  processedVideos: number;
  processedShorts: number;
  lastError?: BatchFailure;
}

export interface SearchResult {
  type: SearchResultKind;
  id: string;
  title: string;
  channelName?: string;
  lengthText?: string;
  viewCount?: string;
}

export interface SearchResults {
  query: string;
  results: SearchResult[];
  count: number;
}

export interface RelatedVideo {
  id: string;
  title: string;
  channelName?: string;
  viewCount?: string;
  lengthText?: string;
}

export interface RelatedResult {
  videoId: string;
  related: RelatedVideo[];
  count: number;
}

export interface TranscriptHit {
  segment: TranscriptSegment;
  index: number;
  context?: string[];
}

export interface TranscriptSearchResult {
  videoId: string;
  query: string;
  matchCount: number;
  hits: TranscriptHit[];
}

export interface SubtitleExport {
  videoId: string;
  /** One of `SubtitleFormat`. */
  format: string;
  languageCode: string;
  segmentCount: number;
  content: string;
  source?: string;
  warnings?: string[];
  path?: string;
}

export interface HeatmapPoint {
  startSeconds: number;
  timestamp: string;
  value: number;
}

export interface HeatmapResult {
  videoId: string;
  points: HeatmapPoint[];
  count: number;
  available: boolean;
}

export interface StoryboardLevel {
  width: number;
  height: number;
  columns: number;
  rows: number;
  intervalMs: number;
  storyboardCount: number;
  templateUrl: string;
  urls: string[];
}

export interface StoryboardsResult {
  videoId: string;
  levels: StoryboardLevel[];
  count: number;
  available: boolean;
}

export interface ManifestsResult {
  videoId: string;
  isLive: boolean;
  dashManifestUrl: string | null;
  hlsManifestUrl: string | null;
  innertubeClient: string;
  note?: string;
}

export interface ClientProbe {
  client: string;
  status: string;
  trackCount: number;
  error?: string;
}

export interface CaptionTrackBrief {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
  sourceClient?: string;
  altUrlCount?: number;
}

export interface SelectedTrackInfo {
  languageCode: string;
  source: string;
  translatedFrom?: string;
  warnings?: string[];
}

export interface TranscriptDiagnosis {
  videoId: string;
  ok: boolean;
  clients: ClientProbe[];
  tracks?: CaptionTrackBrief[];
  selected?: SelectedTrackInfo;
  bodyBytes?: number;
  formatUsed?: string;
  segmentCount?: number;
  cacheHit: boolean;
  staleAvailable: boolean;
  rateBudgetRemaining: number;
  poTokenConfigured: boolean;
  hl: string;
  gl: string;
  error?: string;
  attempts?: string[];
  /** Whether the headless-browser fallback is enabled (YTUBE_BROWSER / opt). */
  browserConfigured?: boolean;
  /** Whether Playwright is installed so the browser fallback can actually run. */
  browserAvailable?: boolean;
}

/** Controls transcript fetching and presentation. */
export interface TranscriptOptions {
  /** Language code or comma-separated preference chain, e.g. `"hi,en"`. */
  lang?: string;
  /** Merge mid-phrase cues into sentences; defaults to true for ASR tracks only. */
  merge?: boolean;
  /** Hard-fail when the requested language is missing (default: best effort). */
  strict?: boolean;
  /** Include word-level timings from json3 captions. */
  words?: boolean;
  /** Force YouTube auto-translation into this language. */
  translateTo?: string;
  /** Drop `[Music]` / `[Applause]` style sound-tag cues. */
  stripSoundTags?: boolean;
  /** Attach chapter-bucketed transcript sections. */
  groupByChapters?: boolean;
  /**
   * Enable the headless-browser caption fallback when Node timedtext GETs are
   * IP-blocked. Requires the optional `playwright` peer dependency. Also
   * enabled globally via `YTUBE_BROWSER=1`.
   */
  browser?: boolean;
}

/** Paging window applied on top of a fetched transcript. */
export interface TranscriptPageOptions {
  /** Segment index to start from; use the previous page's `nextCursor`. */
  cursor?: number;
  /** Characters per page; omit for the whole transcript at once. */
  maxChars?: number;
}

/** Controls how a video pack is assembled. */
export interface PackOptions {
  lang?: string;
  chunkChars?: number;
  /** Remove SponsorBlock-flagged ranges from the chunked text. */
  skipSponsors?: boolean;
}

/** Controls batch pack sizing and resume position. */
export interface BatchOptions extends PackOptions {
  /** Videos processed in this call; kept small because each costs several requests. */
  limit?: number;
  /** Index into the resolved source list, from a previous `nextCursor`. */
  cursor?: number;
  /** Embed full chunk text; disable for a cheap table of contents. */
  includeChunks?: boolean;
  /** For channel sources, select both tabs, long-form videos, or Shorts. */
  contentType?: ChannelCatalogContentFilter;
  /** `analysis` embeds metadata, transcript, chapters, and RAG chunks. */
  detail?: BatchDetail;
}

export interface AskOptions {
  lang?: string;
  /** Passages to return (default 5). */
  topK?: number;
  chunkChars?: number;
}

/** Controls comment paging, ordering, and reply expansion. */
export interface CommentsOptions {
  limit?: number;
  sort?: CommentSort;
  /** Resume token from a previous call's `nextCursor`. */
  cursor?: string;
  /** Threads whose replies get fetched; each costs one extra request. */
  replies?: number;
}
