// Package youtube implements a native YouTube extraction engine.
//
// It is modeled on the approach used by yt-dlp: talk to YouTube's internal
// "InnerTube" API with mobile client identities (ANDROID / IOS), which return
// playable metadata, caption tracks and (usually) direct stream URLs without
// requiring the sig/nsig JavaScript challenges that the WEB client enforces.
// No yt-dlp, Python, or third-party YouTube libraries are used.
package youtube

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"
)

const androidUserAgent = "com.google.android.youtube/20.10.38 (Linux; U; Android 14) gzip"

var videoIDPattern = regexp.MustCompile(`^[A-Za-z0-9_-]{11}$`)

// ExtractError is a structured, machine-readable error. Every failure path
// produces one so the MCP layer can surface clear messages.
type ExtractError struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	Details   map[string]any `json:"details,omitempty"`
	Retryable bool           `json:"retryable"`
}

func (e *ExtractError) Error() string { return e.Code + ": " + e.Message }

// Thumbnail is a single thumbnail rendition.
type Thumbnail struct {
	URL    string `json:"url"`
	Width  int    `json:"width,omitempty"`
	Height int    `json:"height,omitempty"`
}

// VideoInfo is normalized single-video metadata.
type VideoInfo struct {
	ID              string      `json:"id"`
	URL             string      `json:"url"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	ChannelID       string      `json:"channelId"`
	ChannelName     string      `json:"channelName"`
	DurationSeconds int         `json:"durationSeconds"`
	ViewCount       uint64      `json:"viewCount,omitempty"`
	PublishDate     string      `json:"publishDate,omitempty"`
	Category        string      `json:"category,omitempty"`
	Keywords        []string    `json:"keywords,omitempty"`
	IsLive          bool        `json:"isLive"`
	Thumbnails      []Thumbnail `json:"thumbnails"`
}

// CaptionTrack describes one available caption/subtitle track.
type CaptionTrack struct {
	LanguageCode    string `json:"languageCode"`
	Name            string `json:"name"`
	IsAutoGenerated bool   `json:"isAutoGenerated"`
	IsTranslatable  bool   `json:"isTranslatable"`
	BaseURL         string `json:"-"`
}

// TranscriptSegment is one timed caption line.
type TranscriptSegment struct {
	Text     string  `json:"text"`
	Start    float64 `json:"start"`
	Duration float64 `json:"duration"`
}

// Transcript is a full fetched transcript.
type Transcript struct {
	VideoID         string              `json:"videoId"`
	LanguageCode    string              `json:"languageCode"`
	LanguageName    string              `json:"languageName"`
	IsAutoGenerated bool                `json:"isAutoGenerated"`
	SegmentCount    int                 `json:"segmentCount"`
	Segments        []TranscriptSegment `json:"segments"`
	Text            string              `json:"text"`
}

// Chapter is one chapter parsed from the video description.
type Chapter struct {
	Title        string `json:"title"`
	StartSeconds int    `json:"startSeconds"`
	Timestamp    string `json:"timestamp"`
}

// Format describes one downloadable stream variant.
type Format struct {
	Itag          int    `json:"itag"`
	MimeType      string `json:"mimeType"`
	Quality       string `json:"quality,omitempty"`
	QualityLabel  string `json:"qualityLabel,omitempty"`
	AudioQuality  string `json:"audioQuality,omitempty"`
	Bitrate       int    `json:"bitrate,omitempty"`
	ContentLength uint64 `json:"contentLength,omitempty"`
	HasAudio      bool   `json:"hasAudio"`
	HasVideo      bool   `json:"hasVideo"`
	DirectURL     bool   `json:"directUrl"`
	StreamURL     string `json:"-"`
}

// DownloadResult reports a completed media download.
type DownloadResult struct {
	Path         string `json:"path"`
	Itag         int    `json:"itag"`
	MimeType     string `json:"mimeType"`
	BytesWritten int64  `json:"bytesWritten"`
}

// Client performs extraction with a shared HTTP client.
type Client struct{ http *http.Client }

// NewClient builds a Client with the given timeout (default 30s).
func NewClient(timeout time.Duration) *Client {
	if timeout <= 0 {
		timeout = 30 * time.Second
	}
	return &Client{http: &http.Client{Timeout: timeout}}
}

// ParseVideoID accepts a bare 11-char ID or any common YouTube URL shape
// (watch, youtu.be, shorts, embed, live, music) and returns the video ID.
func ParseVideoID(input string) (string, error) {
	input = strings.TrimSpace(input)
	if videoIDPattern.MatchString(input) {
		return input, nil
	}
	if !strings.Contains(input, "://") && strings.Contains(input, "youtu") {
		input = "https://" + input
	}
	u, err := url.Parse(input)
	if err != nil || u.Host == "" {
		return "", invalidVideoError(input)
	}
	host := strings.TrimPrefix(strings.ToLower(u.Hostname()), "www.")
	var candidate string
	switch host {
	case "youtu.be":
		candidate = strings.Split(strings.Trim(u.Path, "/"), "/")[0]
	case "youtube.com", "m.youtube.com", "music.youtube.com", "youtube-nocookie.com":
		candidate = u.Query().Get("v")
		if candidate == "" {
			parts := strings.Split(strings.Trim(u.Path, "/"), "/")
			if len(parts) >= 2 {
				switch parts[0] {
				case "shorts", "embed", "live", "v":
					candidate = parts[1]
				}
			}
		}
	default:
		return "", invalidVideoError(input)
	}
	if !videoIDPattern.MatchString(candidate) {
		return "", invalidVideoError(input)
	}
	return candidate, nil
}

func invalidVideoError(input string) *ExtractError {
	return &ExtractError{
		Code:    "INVALID_VIDEO",
		Message: "Expected an 11-character YouTube video ID or a supported YouTube URL (watch, youtu.be, shorts, embed, live)",
		Details: map[string]any{"input": input},
	}
}

type rawCaptionTrack struct {
	BaseURL        string `json:"baseUrl"`
	LanguageCode   string `json:"languageCode"`
	Kind           string `json:"kind"`
	IsTranslatable bool   `json:"isTranslatable"`
	Name           struct {
		SimpleText string `json:"simpleText"`
		Runs       []struct {
			Text string `json:"text"`
		} `json:"runs"`
	} `json:"name"`
}

func (t rawCaptionTrack) displayName() string {
	if t.Name.SimpleText != "" {
		return t.Name.SimpleText
	}
	var b strings.Builder
	for _, run := range t.Name.Runs {
		b.WriteString(run.Text)
	}
	return b.String()
}

type rawFormat struct {
	Itag            int    `json:"itag"`
	URL             string `json:"url"`
	SignatureCipher string `json:"signatureCipher"`
	MimeType        string `json:"mimeType"`
	Bitrate         int    `json:"bitrate"`
	Quality         string `json:"quality"`
	QualityLabel    string `json:"qualityLabel"`
	AudioQuality    string `json:"audioQuality"`
	ContentLength   string `json:"contentLength"`
}

type playerResponse struct {
	PlayabilityStatus struct {
		Status      string `json:"status"`
		Reason      string `json:"reason"`
		ErrorScreen struct {
			PlayerErrorMessageRenderer struct {
				Reason struct {
					SimpleText string `json:"simpleText"`
				} `json:"reason"`
			} `json:"playerErrorMessageRenderer"`
		} `json:"errorScreen"`
	} `json:"playabilityStatus"`
	VideoDetails struct {
		VideoID          string   `json:"videoId"`
		Title            string   `json:"title"`
		LengthSeconds    string   `json:"lengthSeconds"`
		Keywords         []string `json:"keywords"`
		ChannelID        string   `json:"channelId"`
		ShortDescription string   `json:"shortDescription"`
		ViewCount        string   `json:"viewCount"`
		Author           string   `json:"author"`
		IsLiveContent    bool     `json:"isLiveContent"`
		Thumbnail        struct {
			Thumbnails []Thumbnail `json:"thumbnails"`
		} `json:"thumbnail"`
	} `json:"videoDetails"`
	Microformat struct {
		PlayerMicroformatRenderer struct {
			PublishDate string `json:"publishDate"`
			Category    string `json:"category"`
		} `json:"playerMicroformatRenderer"`
	} `json:"microformat"`
	Captions struct {
		PlayerCaptionsTracklistRenderer struct {
			CaptionTracks []rawCaptionTrack `json:"captionTracks"`
		} `json:"playerCaptionsTracklistRenderer"`
	} `json:"captions"`
	StreamingData struct {
		Formats         []rawFormat `json:"formats"`
		AdaptiveFormats []rawFormat `json:"adaptiveFormats"`
	} `json:"streamingData"`
}

type innertubeClient struct {
	Name      string
	Version   string
	NumericID string
	UserAgent string
	OSName    string
	OSVersion string
	SDKInt    int
}

// Client identities mirror yt-dlp's INNERTUBE_CLIENTS table. ANDROID and IOS
// are preferred because their responses avoid WEB's sig/nsig + PO-token gates.
var innertubeClients = []innertubeClient{
	{Name: "ANDROID", Version: "20.10.38", NumericID: "3", UserAgent: androidUserAgent, OSName: "Android", OSVersion: "14", SDKInt: 34},
	{Name: "IOS", Version: "20.10.4", NumericID: "5", UserAgent: "com.google.ios.youtube/20.10.4 (iPhone16,2; U; CPU iOS 18_3_2 like Mac OS X;)", OSName: "iOS", OSVersion: "18.3.2.22D82"},
	{Name: "WEB", Version: "2.20250312.04.00", NumericID: "1", UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"},
}

// fetchPlayer tries each InnerTube client until one returns a playable
// response, mirroring yt-dlp's client-fallback strategy.
func (c *Client) fetchPlayer(ctx context.Context, videoID string) (*playerResponse, string, error) {
	var attempts []string
	for _, profile := range innertubeClients {
		p, err := c.fetchPlayerWith(ctx, videoID, profile)
		if err != nil {
			attempts = append(attempts, profile.Name+": "+err.Error())
			continue
		}
		if p.PlayabilityStatus.Status == "OK" && p.VideoDetails.VideoID != "" {
			return p, profile.Name, nil
		}
		reason := p.PlayabilityStatus.Reason
		if reason == "" {
			reason = p.PlayabilityStatus.ErrorScreen.PlayerErrorMessageRenderer.Reason.SimpleText
		}
		attempts = append(attempts, fmt.Sprintf("%s: %s (%s)", profile.Name, p.PlayabilityStatus.Status, reason))
	}
	return nil, "", classifyPlayabilityFailure(videoID, attempts)
}

func classifyPlayabilityFailure(videoID string, attempts []string) *ExtractError {
	joined := strings.ToLower(strings.Join(attempts, " | "))
	code, message, retryable := "VIDEO_UNAVAILABLE", "YouTube did not return a playable response for this video", false
	switch {
	case strings.Contains(joined, "login_required") || strings.Contains(joined, "sign in") || strings.Contains(joined, "age"):
		code = "AUTH_REQUIRED"
		message = "This video requires sign-in or age verification, which this extractor does not support"
	case strings.Contains(joined, "private"):
		code = "PRIVATE_VIDEO"
		message = "This video is private"
	case strings.Contains(joined, "unavailable") || strings.Contains(joined, "removed"):
		code = "VIDEO_UNAVAILABLE"
		message = "This video is unavailable (deleted, region-blocked, or the ID does not exist)"
	case strings.Contains(joined, "rate") || strings.Contains(joined, "429"):
		code, retryable = "RATE_LIMITED", true
		message = "YouTube rate-limited the request; wait a few minutes and retry"
	case strings.Contains(joined, "live"):
		code = "LIVE_NOT_SUPPORTED"
		message = "Live streams are not supported by this extractor"
	}
	return &ExtractError{Code: code, Message: message, Retryable: retryable,
		Details: map[string]any{"videoId": videoID, "attempts": attempts}}
}

func (c *Client) fetchPlayerWith(ctx context.Context, videoID string, profile innertubeClient) (*playerResponse, error) {
	clientCtx := map[string]any{
		"clientName":    profile.Name,
		"clientVersion": profile.Version,
		"hl":            "en",
		"gl":            "US",
	}
	if profile.OSName != "" {
		clientCtx["osName"] = profile.OSName
		clientCtx["osVersion"] = profile.OSVersion
	}
	if profile.SDKInt > 0 {
		clientCtx["androidSdkVersion"] = profile.SDKInt
	}
	body, _ := json.Marshal(map[string]any{
		"videoId":        videoID,
		"contentCheckOk": true,
		"racyCheckOk":    true,
		"context":        map[string]any{"client": clientCtx},
	})
	endpoint := "https://www.youtube.com/youtubei/v1/player?prettyPrint=false"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, strings.NewReader(string(body)))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("User-Agent", profile.UserAgent)
	req.Header.Set("X-YouTube-Client-Name", profile.NumericID)
	req.Header.Set("X-YouTube-Client-Version", profile.Version)
	req.Header.Set("Origin", "https://www.youtube.com")
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, classifyNetworkError(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, httpStatusError(resp.StatusCode)
	}
	var result playerResponse
	if err := json.NewDecoder(io.LimitReader(resp.Body, 32<<20)).Decode(&result); err != nil {
		return nil, &ExtractError{Code: "INVALID_RESPONSE", Retryable: true,
			Message: "YouTube returned malformed player data", Details: map[string]any{"cause": err.Error()}}
	}
	return &result, nil
}

func classifyNetworkError(err error) error {
	if errors.Is(err, context.DeadlineExceeded) || os.IsTimeout(err) {
		return &ExtractError{Code: "TIMEOUT", Message: "The YouTube request timed out", Retryable: true,
			Details: map[string]any{"cause": err.Error()}}
	}
	return &ExtractError{Code: "NETWORK_ERROR", Message: "Could not connect to YouTube (check your internet connection or proxy)",
		Retryable: true, Details: map[string]any{"cause": err.Error()}}
}

func httpStatusError(status int) *ExtractError {
	switch status {
	case http.StatusTooManyRequests:
		return &ExtractError{Code: "RATE_LIMITED", Message: "YouTube rate-limited the request (HTTP 429); wait and retry", Retryable: true,
			Details: map[string]any{"status": status}}
	case http.StatusForbidden:
		return &ExtractError{Code: "ACCESS_DENIED", Message: "YouTube denied the request (HTTP 403); this client may now require a PO token",
			Details: map[string]any{"status": status}}
	default:
		return &ExtractError{Code: "YOUTUBE_HTTP_ERROR", Message: fmt.Sprintf("YouTube returned HTTP %d", status),
			Retryable: status >= 500, Details: map[string]any{"status": status}}
	}
}

// Info returns normalized metadata for one video.
func (c *Client) Info(ctx context.Context, input string) (*VideoInfo, error) {
	id, err := ParseVideoID(input)
	if err != nil {
		return nil, err
	}
	p, _, err := c.fetchPlayer(ctx, id)
	if err != nil {
		return nil, err
	}
	return infoFromPlayer(id, p), nil
}

func infoFromPlayer(id string, p *playerResponse) *VideoInfo {
	duration, _ := strconv.Atoi(p.VideoDetails.LengthSeconds)
	views, _ := strconv.ParseUint(p.VideoDetails.ViewCount, 10, 64)
	return &VideoInfo{
		ID:              id,
		URL:             "https://www.youtube.com/watch?v=" + id,
		Title:           p.VideoDetails.Title,
		Description:     p.VideoDetails.ShortDescription,
		ChannelID:       p.VideoDetails.ChannelID,
		ChannelName:     p.VideoDetails.Author,
		DurationSeconds: duration,
		ViewCount:       views,
		PublishDate:     p.Microformat.PlayerMicroformatRenderer.PublishDate,
		Category:        p.Microformat.PlayerMicroformatRenderer.Category,
		Keywords:        p.VideoDetails.Keywords,
		IsLive:          p.VideoDetails.IsLiveContent,
		Thumbnails:      p.VideoDetails.Thumbnail.Thumbnails,
	}
}

func captionsFromPlayer(p *playerResponse) []CaptionTrack {
	raw := p.Captions.PlayerCaptionsTracklistRenderer.CaptionTracks
	tracks := make([]CaptionTrack, 0, len(raw))
	for _, t := range raw {
		tracks = append(tracks, CaptionTrack{
			LanguageCode:    t.LanguageCode,
			Name:            t.displayName(),
			IsAutoGenerated: t.Kind == "asr",
			IsTranslatable:  t.IsTranslatable,
			BaseURL:         t.BaseURL,
		})
	}
	return tracks
}

// ListCaptions lists available caption tracks for a video.
func (c *Client) ListCaptions(ctx context.Context, input string) ([]CaptionTrack, error) {
	id, err := ParseVideoID(input)
	if err != nil {
		return nil, err
	}
	p, _, err := c.fetchPlayer(ctx, id)
	if err != nil {
		return nil, err
	}
	return captionsFromPlayer(p), nil
}

// pickCaptionTrack selects the best track for lang: exact manual > exact ASR >
// prefix match. With lang=="" it prefers the first manual track.
func pickCaptionTrack(tracks []CaptionTrack, lang string) (*CaptionTrack, error) {
	if len(tracks) == 0 {
		return nil, &ExtractError{Code: "NO_CAPTIONS",
			Message: "This video has no caption tracks (the uploader disabled them or YouTube has not generated any)"}
	}
	if lang == "" {
		for i := range tracks {
			if !tracks[i].IsAutoGenerated {
				return &tracks[i], nil
			}
		}
		return &tracks[0], nil
	}
	lang = strings.ToLower(lang)
	var exactASR, prefix *CaptionTrack
	for i := range tracks {
		code := strings.ToLower(tracks[i].LanguageCode)
		switch {
		case code == lang && !tracks[i].IsAutoGenerated:
			return &tracks[i], nil
		case code == lang && exactASR == nil:
			exactASR = &tracks[i]
		case strings.HasPrefix(code, lang+"-") && prefix == nil:
			prefix = &tracks[i]
		}
	}
	if exactASR != nil {
		return exactASR, nil
	}
	if prefix != nil {
		return prefix, nil
	}
	available := make([]string, len(tracks))
	for i, t := range tracks {
		available[i] = t.LanguageCode
	}
	return nil, &ExtractError{Code: "LANGUAGE_NOT_AVAILABLE",
		Message: fmt.Sprintf("No caption track for language %q; available languages: %s", lang, strings.Join(available, ", ")),
		Details: map[string]any{"requested": lang, "available": available}}
}

// Transcript downloads and parses the caption track for lang ("" = best).
func (c *Client) Transcript(ctx context.Context, input, lang string) (*Transcript, error) {
	id, err := ParseVideoID(input)
	if err != nil {
		return nil, err
	}
	p, _, err := c.fetchPlayer(ctx, id)
	if err != nil {
		return nil, err
	}
	track, err := pickCaptionTrack(captionsFromPlayer(p), lang)
	if err != nil {
		return nil, err
	}
	segments, err := c.fetchCaptionSegments(ctx, track.BaseURL)
	if err != nil {
		return nil, err
	}
	if len(segments) == 0 {
		return nil, &ExtractError{Code: "EMPTY_TRANSCRIPT", Retryable: true,
			Message: "YouTube returned an empty caption body; the track may be PO-token gated on this client. Retry, or try another language."}
	}
	var b strings.Builder
	for i, s := range segments {
		if i > 0 {
			b.WriteByte(' ')
		}
		b.WriteString(s.Text)
	}
	return &Transcript{
		VideoID:         id,
		LanguageCode:    track.LanguageCode,
		LanguageName:    track.Name,
		IsAutoGenerated: track.IsAutoGenerated,
		SegmentCount:    len(segments),
		Segments:        segments,
		Text:            b.String(),
	}, nil
}

var fmtParamPattern = regexp.MustCompile(`fmt=\w+`)

// fetchCaptionSegments downloads a caption track, trying json3 first and
// falling back to the default XML (srv1) format, like yt-dlp does.
func (c *Client) fetchCaptionSegments(ctx context.Context, baseURL string) ([]TranscriptSegment, error) {
	json3URL := baseURL
	if fmtParamPattern.MatchString(json3URL) {
		json3URL = fmtParamPattern.ReplaceAllString(json3URL, "fmt=json3")
	} else {
		json3URL += "&fmt=json3"
	}
	if segs, err := c.fetchJSON3(ctx, json3URL); err == nil && len(segs) > 0 {
		return segs, nil
	}
	return c.fetchTimedTextXML(ctx, baseURL)
}

func (c *Client) captionGet(ctx context.Context, u string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", androidUserAgent)
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, classifyNetworkError(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, httpStatusError(resp.StatusCode)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 32<<20))
}

type json3Body struct {
	Events []struct {
		TStartMs    float64 `json:"tStartMs"`
		DDurationMs float64 `json:"dDurationMs"`
		Segs        []struct {
			UTF8 string `json:"utf8"`
		} `json:"segs"`
	} `json:"events"`
}

func (c *Client) fetchJSON3(ctx context.Context, u string) ([]TranscriptSegment, error) {
	data, err := c.captionGet(ctx, u)
	if err != nil {
		return nil, err
	}
	var body json3Body
	if err := json.Unmarshal(data, &body); err != nil {
		return nil, err
	}
	var segments []TranscriptSegment
	for _, ev := range body.Events {
		var b strings.Builder
		for _, s := range ev.Segs {
			b.WriteString(s.UTF8)
		}
		text := normalizeCaptionText(b.String())
		if text == "" {
			continue
		}
		segments = append(segments, TranscriptSegment{
			Text:     text,
			Start:    ev.TStartMs / 1000,
			Duration: ev.DDurationMs / 1000,
		})
	}
	return segments, nil
}

func normalizeCaptionText(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.Join(strings.Fields(s), " ")
}
