// Package youtube implements a native YouTube extraction engine.
//
// It is modeled on the approach used by yt-dlp: talk to YouTube's internal
// "InnerTube" API with mobile client identities (ANDROID / IOS), which return
// playable metadata, caption tracks and (usually) direct stream URLs without
// requiring the sig/nsig JavaScript challenges that the WEB client enforces.
// No yt-dlp, Python, or third-party YouTube libraries are used.
package youtube

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"regexp"
	"strconv"
	"strings"
)

var videoIDPattern = regexp.MustCompile(`^[A-Za-z0-9_-]{11}$`)

// ExtractError is a structured, machine-readable error. Every failure path
// produces one so the MCP layer can surface clear messages.
type ExtractError struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	Details   map[string]any `json:"details,omitempty"`
	Retryable bool           `json:"retryable"`
}

func (e *ExtractError) Error() string { return e.Code + ": " + e.Message }

// Thumbnail is a single thumbnail rendition.
type Thumbnail struct {
	URL    string `json:"url"`
	Width  int    `json:"width,omitempty"`
	Height int    `json:"height,omitempty"`
}

// VideoInfo is normalized single-video metadata.
type VideoInfo struct {
	ID              string      `json:"id"`
	URL             string      `json:"url"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	ChannelID       string      `json:"channelId"`
	ChannelName     string      `json:"channelName"`
	DurationSeconds int         `json:"durationSeconds"`
	ViewCount       uint64      `json:"viewCount,omitempty"`
	PublishDate     string      `json:"publishDate,omitempty"`
	Category        string      `json:"category,omitempty"`
	Keywords        []string    `json:"keywords,omitempty"`
	IsLive          bool        `json:"isLive"`
	Thumbnails      []Thumbnail `json:"thumbnails"`
}

// CaptionTrack describes one available caption/subtitle track.
type CaptionTrack struct {
	LanguageCode    string `json:"languageCode"`
	Name            string `json:"name"`
	IsAutoGenerated bool   `json:"isAutoGenerated"`
	IsTranslatable  bool   `json:"isTranslatable"`
	BaseURL         string `json:"-"`
}

// TranscriptSegment is one timed caption line with human-readable timestamps.
type TranscriptSegment struct {
	Text         string  `json:"text"`
	Start        float64 `json:"start"`
	Duration     float64 `json:"duration"`
	End          float64 `json:"end"`
	Timestamp    string  `json:"timestamp"`
	TimestampEnd string  `json:"timestampEnd"`
}

// Transcript is a full fetched transcript.
type Transcript struct {
	VideoID         string              `json:"videoId"`
	LanguageCode    string              `json:"languageCode"`
	LanguageName    string              `json:"languageName"`
	IsAutoGenerated bool                `json:"isAutoGenerated"`
	TranslatedFrom  string              `json:"translatedFrom,omitempty"`
	Merged          bool                `json:"merged"`
	RawSegmentCount int                 `json:"rawSegmentCount"`
	SegmentCount    int                 `json:"segmentCount"`
	DurationSeconds float64             `json:"durationSeconds"`
	Segments        []TranscriptSegment `json:"segments"`
	Lines           []string            `json:"lines"`
	Text            string              `json:"text"`
}

// Chapter is one chapter marker.
type Chapter struct {
	Title        string `json:"title"`
	StartSeconds int    `json:"startSeconds"`
	Timestamp    string `json:"timestamp"`
}

// Format describes one downloadable stream variant.
type Format struct {
	Itag          int    `json:"itag"`
	MimeType      string `json:"mimeType"`
	Quality       string `json:"quality,omitempty"`
	QualityLabel  string `json:"qualityLabel,omitempty"`
	AudioQuality  string `json:"audioQuality,omitempty"`
	Bitrate       int    `json:"bitrate,omitempty"`
	ContentLength uint64 `json:"contentLength,omitempty"`
	HasAudio      bool   `json:"hasAudio"`
	HasVideo      bool   `json:"hasVideo"`
	DirectURL     bool   `json:"directUrl"`
	StreamURL     string `json:"-"`
}

// DownloadResult reports a completed media download.
type DownloadResult struct {
	Path         string `json:"path"`
	Itag         int    `json:"itag"`
	MimeType     string `json:"mimeType"`
	BytesWritten int64  `json:"bytesWritten"`
}

// ParseVideoID accepts a bare 11-char ID or any common YouTube URL shape
// (watch, youtu.be, shorts, embed, live, music) and returns the video ID.
func ParseVideoID(input string) (string, error) {
	input = strings.TrimSpace(input)
	if videoIDPattern.MatchString(input) {
		return input, nil
	}
	if !strings.Contains(input, "://") && strings.Contains(input, "youtu") {
		input = "https://" + input
	}
	u, err := url.Parse(input)
	if err != nil || u.Host == "" {
		return "", invalidVideoError(input)
	}
	host := strings.TrimPrefix(strings.ToLower(u.Hostname()), "www.")
	var candidate string
	switch host {
	case "youtu.be":
		candidate = strings.Split(strings.Trim(u.Path, "/"), "/")[0]
	case "youtube.com", "m.youtube.com", "music.youtube.com", "youtube-nocookie.com":
		candidate = u.Query().Get("v")
		if candidate == "" {
			parts := strings.Split(strings.Trim(u.Path, "/"), "/")
			if len(parts) >= 2 {
				switch parts[0] {
				case "shorts", "embed", "live", "v":
					candidate = parts[1]
				}
			}
		}
	default:
		return "", invalidVideoError(input)
	}
	if !videoIDPattern.MatchString(candidate) {
		return "", invalidVideoError(input)
	}
	return candidate, nil
}

func invalidVideoError(input string) *ExtractError {
	return &ExtractError{
		Code:    "INVALID_VIDEO",
		Message: "Expected an 11-character YouTube video ID or a supported YouTube URL (watch, youtu.be, shorts, embed, live)",
		Details: map[string]any{"input": input},
	}
}

type rawCaptionTrack struct {
	BaseURL        string `json:"baseUrl"`
	LanguageCode   string `json:"languageCode"`
	Kind           string `json:"kind"`
	IsTranslatable bool   `json:"isTranslatable"`
	Name           struct {
		SimpleText string `json:"simpleText"`
		Runs       []struct {
			Text string `json:"text"`
		} `json:"runs"`
	} `json:"name"`
}

func (t rawCaptionTrack) displayName() string {
	if t.Name.SimpleText != "" {
		return t.Name.SimpleText
	}
	var b strings.Builder
	for _, run := range t.Name.Runs {
		b.WriteString(run.Text)
	}
	return b.String()
}

type rawFormat struct {
	Itag            int    `json:"itag"`
	URL             string `json:"url"`
	SignatureCipher string `json:"signatureCipher"`
	MimeType        string `json:"mimeType"`
	Bitrate         int    `json:"bitrate"`
	Quality         string `json:"quality"`
	QualityLabel    string `json:"qualityLabel"`
	AudioQuality    string `json:"audioQuality"`
	ContentLength   string `json:"contentLength"`
}

type playerResponse struct {
	PlayabilityStatus struct {
		Status      string `json:"status"`
		Reason      string `json:"reason"`
		ErrorScreen struct {
			PlayerErrorMessageRenderer struct {
				Reason struct {
					SimpleText string `json:"simpleText"`
				} `json:"reason"`
			} `json:"playerErrorMessageRenderer"`
		} `json:"errorScreen"`
	} `json:"playabilityStatus"`
	VideoDetails struct {
		VideoID          string   `json:"videoId"`
		Title            string   `json:"title"`
		LengthSeconds    string   `json:"lengthSeconds"`
		Keywords         []string `json:"keywords"`
		ChannelID        string   `json:"channelId"`
		ShortDescription string   `json:"shortDescription"`
		ViewCount        string   `json:"viewCount"`
		Author           string   `json:"author"`
		IsLiveContent    bool     `json:"isLiveContent"`
		Thumbnail        struct {
			Thumbnails []Thumbnail `json:"thumbnails"`
		} `json:"thumbnail"`
	} `json:"videoDetails"`
	Microformat struct {
		PlayerMicroformatRenderer struct {
			PublishDate string `json:"publishDate"`
			Category    string `json:"category"`
		} `json:"playerMicroformatRenderer"`
	} `json:"microformat"`
	Captions struct {
		PlayerCaptionsTracklistRenderer struct {
			CaptionTracks []rawCaptionTrack `json:"captionTracks"`
		} `json:"playerCaptionsTracklistRenderer"`
	} `json:"captions"`
	StreamingData struct {
		Formats         []rawFormat `json:"formats"`
		AdaptiveFormats []rawFormat `json:"adaptiveFormats"`
		DashManifestURL string      `json:"dashManifestUrl"`
		HlsManifestURL  string      `json:"hlsManifestUrl"`
	} `json:"streamingData"`
	Storyboards struct {
		PlayerStoryboardSpecRenderer struct {
			Spec string `json:"spec"`
		} `json:"playerStoryboardSpecRenderer"`
	} `json:"storyboards"`
}

// fetchPlayer tries each InnerTube client until one returns a playable
// response, mirroring yt-dlp's client-fallback strategy.
func (c *Client) fetchPlayer(ctx context.Context, videoID string) (*playerResponse, string, error) {
	var attempts []string
	for _, profile := range playerClients {
		var p playerResponse
		err := c.callJSON(ctx, "player", profile, map[string]any{
			"videoId": videoID, "contentCheckOk": true, "racyCheckOk": true,
		}, &p)
		if err != nil {
			attempts = append(attempts, profile.Name+": "+err.Error())
			continue
		}
		if p.PlayabilityStatus.Status == "OK" && p.VideoDetails.VideoID != "" {
			return &p, profile.Name, nil
		}
		reason := p.PlayabilityStatus.Reason
		if reason == "" {
			reason = p.PlayabilityStatus.ErrorScreen.PlayerErrorMessageRenderer.Reason.SimpleText
		}
		attempts = append(attempts, fmt.Sprintf("%s: %s (%s)", profile.Name, p.PlayabilityStatus.Status, reason))
	}
	return nil, "", classifyPlayabilityFailure(videoID, attempts)
}

func classifyPlayabilityFailure(videoID string, attempts []string) *ExtractError {
	joined := strings.ToLower(strings.Join(attempts, " | "))
	code, message, retryable := "VIDEO_UNAVAILABLE", "YouTube did not return a playable response for this video", false
	switch {
	case strings.Contains(joined, "login_required") || strings.Contains(joined, "sign in") || strings.Contains(joined, "age"):
		code = "AUTH_REQUIRED"
		message = "This video requires sign-in or age verification; pass cookies via --cookies or YTUBE_COOKIES"
	case strings.Contains(joined, "private"):
		code = "PRIVATE_VIDEO"
		message = "This video is private"
	case strings.Contains(joined, "unavailable") || strings.Contains(joined, "removed"):
		code = "VIDEO_UNAVAILABLE"
		message = "This video is unavailable (deleted, region-blocked, or the ID does not exist)"
	case strings.Contains(joined, "rate") || strings.Contains(joined, "429"):
		code, retryable = "RATE_LIMITED", true
		message = "YouTube rate-limited the request; wait a few minutes and retry"
	case strings.Contains(joined, "live"):
		code = "LIVE_NOT_SUPPORTED"
		message = "Live streams are not supported by this extractor"
	}
	return &ExtractError{Code: code, Message: message, Retryable: retryable,
		Details: map[string]any{"videoId": videoID, "attempts": attempts}}
}

// Info returns normalized metadata for one video.
func (c *Client) Info(ctx context.Context, input string) (*VideoInfo, error) {
	id, err := ParseVideoID(input)
	if err != nil {
		return nil, err
	}
	var cached VideoInfo
	if c.cacheGet("info", id, &cached) {
		return &cached, nil
	}
	p, _, err := c.fetchPlayer(ctx, id)
	if err != nil {
		return nil, err
	}
	info := infoFromPlayer(id, p)
	c.cacheSet("info", id, info)
	return info, nil
}

func infoFromPlayer(id string, p *playerResponse) *VideoInfo {
	duration, _ := strconv.Atoi(p.VideoDetails.LengthSeconds)
	views, _ := strconv.ParseUint(p.VideoDetails.ViewCount, 10, 64)
	return &VideoInfo{
		ID:              id,
		URL:             "https://www.youtube.com/watch?v=" + id,
		Title:           p.VideoDetails.Title,
		Description:     p.VideoDetails.ShortDescription,
		ChannelID:       p.VideoDetails.ChannelID,
		ChannelName:     p.VideoDetails.Author,
		DurationSeconds: duration,
		ViewCount:       views,
		PublishDate:     p.Microformat.PlayerMicroformatRenderer.PublishDate,
		Category:        p.Microformat.PlayerMicroformatRenderer.Category,
		Keywords:        p.VideoDetails.Keywords,
		IsLive:          p.VideoDetails.IsLiveContent,
		Thumbnails:      p.VideoDetails.Thumbnail.Thumbnails,
	}
}

func captionsFromPlayer(p *playerResponse) []CaptionTrack {
	raw := p.Captions.PlayerCaptionsTracklistRenderer.CaptionTracks
	tracks := make([]CaptionTrack, 0, len(raw))
	for _, t := range raw {
		tracks = append(tracks, CaptionTrack{
			LanguageCode:    t.LanguageCode,
			Name:            t.displayName(),
			IsAutoGenerated: t.Kind == "asr",
			IsTranslatable:  t.IsTranslatable,
			BaseURL:         t.BaseURL,
		})
	}
	return tracks
}

// ListCaptions lists available caption tracks for a video.
func (c *Client) ListCaptions(ctx context.Context, input string) ([]CaptionTrack, error) {
	id, err := ParseVideoID(input)
	if err != nil {
		return nil, err
	}
	p, _, err := c.fetchPlayer(ctx, id)
	if err != nil {
		return nil, err
	}
	return captionsFromPlayer(p), nil
}

// pickCaptionTrack selects the best track for lang: exact manual > exact ASR >
// prefix match. With lang=="" it prefers the first manual track.
func pickCaptionTrack(tracks []CaptionTrack, lang string) (*CaptionTrack, error) {
	if len(tracks) == 0 {
		return nil, &ExtractError{Code: "NO_CAPTIONS",
			Message: "This video has no caption tracks (the uploader disabled them or YouTube has not generated any)"}
	}
	if lang == "" {
		for i := range tracks {
			if !tracks[i].IsAutoGenerated {
				return &tracks[i], nil
			}
		}
		return &tracks[0], nil
	}
	lang = strings.ToLower(lang)
	var exactASR, prefix *CaptionTrack
	for i := range tracks {
		code := strings.ToLower(tracks[i].LanguageCode)
		switch {
		case code == lang && !tracks[i].IsAutoGenerated:
			return &tracks[i], nil
		case code == lang && exactASR == nil:
			exactASR = &tracks[i]
		case strings.HasPrefix(code, lang+"-") && prefix == nil:
			prefix = &tracks[i]
		}
	}
	if exactASR != nil {
		return exactASR, nil
	}
	if prefix != nil {
		return prefix, nil
	}
	available := make([]string, len(tracks))
	for i, t := range tracks {
		available[i] = t.LanguageCode
	}
	return nil, &ExtractError{Code: "LANGUAGE_NOT_AVAILABLE",
		Message: fmt.Sprintf("No caption track for language %q; available languages: %s", lang, strings.Join(available, ", ")),
		Details: map[string]any{"requested": lang, "available": available}}
}

func enrichSegments(segments []TranscriptSegment) []TranscriptSegment {
	out := make([]TranscriptSegment, len(segments))
	for i, s := range segments {
		end := s.End
		if end <= 0 {
			end = s.Start + s.Duration
		}
		if end < s.Start {
			end = s.Start
		}
		out[i] = TranscriptSegment{
			Text: s.Text, Start: s.Start, Duration: end - s.Start, End: end,
			Timestamp: FormatTimestamp(s.Start), TimestampEnd: FormatTimestamp(end),
		}
	}
	return out
}

// sentenceEnd reports whether text already finishes a sentence/cue cleanly.
func sentenceEnd(text string) bool {
	text = strings.TrimSpace(text)
	if text == "" {
		return false
	}
	runes := []rune(text)
	switch runes[len(runes)-1] {
	case '.', '!', '?', '।', '؟', '…', '♪':
		return true
	case ']': // e.g. [संगीत] / [music]
		return true
	default:
		return false
	}
}

// MergeASRSegments joins YouTube ASR's mid-phrase cue fragments into readable
// sentences. Official timedtext is already complete for the full video length;
// ASR simply chops speech into ~2–4s windows that often end mid-sentence.
func MergeASRSegments(segments []TranscriptSegment) []TranscriptSegment {
	if len(segments) <= 1 {
		return enrichSegments(segments)
	}
	segments = enrichSegments(segments)
	const (
		maxGap      = 1.75
		maxDuration = 45.0
		maxChars    = 500
	)
	var out []TranscriptSegment
	cur := segments[0]
	for i := 1; i < len(segments); i++ {
		next := segments[i]
		span := next.End - cur.Start
		chars := len([]rune(cur.Text)) + 1 + len([]rune(next.Text))
		// ASR cues often overlap in time (rolling windows) while carrying the NEXT
		// phrase only — allow small overlaps and short gaps.
		nearby := next.Start <= cur.End+maxGap && next.Start >= cur.Start-0.05
		if !sentenceEnd(cur.Text) && nearby && span <= maxDuration && chars <= maxChars {
			cur.Text = strings.TrimSpace(cur.Text + " " + next.Text)
			if next.End > cur.End {
				cur.End = next.End
			}
			cur.Duration = cur.End - cur.Start
			continue
		}
		out = append(out, cur)
		cur = next
	}
	out = append(out, cur)
	return enrichSegments(out)
}

func buildTranscript(id string, track *CaptionTrack, segments []TranscriptSegment, merged bool, translatedFrom string) *Transcript {
	rawCount := len(segments)
	if merged {
		segments = MergeASRSegments(segments)
	} else {
		segments = enrichSegments(segments)
	}
	lines := make([]string, len(segments))
	var b strings.Builder
	var duration float64
	for i, s := range segments {
		lines[i] = "[" + s.Timestamp + "] " + s.Text
		if i > 0 {
			b.WriteByte(' ')
		}
		b.WriteString(s.Text)
		if s.End > duration {
			duration = s.End
		}
	}
	name := track.Name
	if translatedFrom != "" {
		name = name + " (translated to " + track.LanguageCode + ")"
	}
	return &Transcript{
		VideoID: id, LanguageCode: track.LanguageCode, LanguageName: name,
		IsAutoGenerated: track.IsAutoGenerated, TranslatedFrom: translatedFrom,
		Merged: merged, RawSegmentCount: rawCount, SegmentCount: len(segments),
		DurationSeconds: duration, Segments: segments, Lines: lines, Text: b.String(),
	}
}

// TranscriptOptions controls transcript fetching/presentation.
type TranscriptOptions struct {
	Lang  string
	Merge *bool // nil = merge auto-generated tracks by default
}

func (o TranscriptOptions) shouldMerge(auto bool) bool {
	if o.Merge != nil {
		return *o.Merge
	}
	return auto // ASR cues are mid-phrase by default; manual tracks usually aren't
}

// Transcript downloads and parses the caption track for lang ("" = best).
// Auto-generated tracks are sentence-merged by default so long videos read
// continuously instead of as chopped 2–4 second fragments.
func (c *Client) Transcript(ctx context.Context, input, lang string) (*Transcript, error) {
	return c.TranscriptWithOptions(ctx, input, TranscriptOptions{Lang: lang})
}

// TranscriptWithOptions is Transcript with explicit merge/language controls.
func (c *Client) TranscriptWithOptions(ctx context.Context, input string, opts TranscriptOptions) (*Transcript, error) {
	id, err := ParseVideoID(input)
	if err != nil {
		return nil, err
	}
	p, _, err := c.fetchPlayer(ctx, id)
	if err != nil {
		return nil, err
	}
	tracks := captionsFromPlayer(p)
	track, err := pickCaptionTrack(tracks, opts.Lang)
	translatedFrom := ""
	captionURL := ""
	if err != nil {
		// Requested language missing: try YouTube's auto-translate (tlang) from any translatable track.
		if opts.Lang != "" {
			base, baseErr := pickCaptionTrack(tracks, "")
			if baseErr == nil && base.IsTranslatable {
				captionURL = withTranscriptLang(base.BaseURL, opts.Lang)
				translatedFrom = base.LanguageCode
				track = &CaptionTrack{
					LanguageCode:    opts.Lang,
					Name:            base.Name,
					IsAutoGenerated: true,
					IsTranslatable:  true,
					BaseURL:         captionURL,
				}
				err = nil
			}
		}
		if err != nil {
			return nil, err
		}
	} else {
		captionURL = track.BaseURL
	}
	segments, err := c.fetchCaptionSegments(ctx, captionURL)
	if err != nil {
		return nil, err
	}
	if len(segments) == 0 {
		code := "EMPTY_TRANSCRIPT"
		msg := "YouTube returned an empty caption body; the track may be PO-token gated on this client. Retry, or try another language."
		if translatedFrom != "" {
			code = "TRANSLATION_UNAVAILABLE"
			msg = fmt.Sprintf("YouTube returned an empty auto-translation to %q from %q", opts.Lang, translatedFrom)
		}
		return nil, &ExtractError{Code: code, Retryable: true, Message: msg}
	}
	merge := opts.shouldMerge(track.IsAutoGenerated || translatedFrom != "")
	cacheKey := id + "|" + opts.Lang + "|" + captionURL + "|" + fmt.Sprintf("%v", merge)
	var cached Transcript
	if c.cacheGet("transcript", cacheKey, &cached) {
		return &cached, nil
	}
	result := buildTranscript(id, track, segments, merge, translatedFrom)
	c.cacheSet("transcript", cacheKey, result)
	return result, nil
}

func withTranscriptLang(baseURL, lang string) string {
	if lang == "" {
		return baseURL
	}
	if strings.Contains(baseURL, "tlang=") {
		return regexp.MustCompile(`tlang=[^&]*`).ReplaceAllString(baseURL, "tlang="+lang)
	}
	sep := "?"
	if strings.Contains(baseURL, "?") {
		sep = "&"
	}
	return baseURL + sep + "tlang=" + lang
}

var fmtParamPattern = regexp.MustCompile(`fmt=\w+`)

// fetchCaptionSegments downloads a caption track, trying json3 first and
// falling back to srv1/srv3 XML formats.
func (c *Client) fetchCaptionSegments(ctx context.Context, baseURL string) ([]TranscriptSegment, error) {
	json3URL := baseURL
	if fmtParamPattern.MatchString(json3URL) {
		json3URL = fmtParamPattern.ReplaceAllString(json3URL, "fmt=json3")
	} else {
		json3URL += "&fmt=json3"
	}
	if segs, err := c.fetchJSON3(ctx, json3URL); err == nil && len(segs) > 0 {
		return segs, nil
	}
	// Prefer classic srv1 <transcript>; also try srv3 <timedtext>.
	for _, fmt := range []string{"srv1", "srv3"} {
		u := baseURL
		if fmtParamPattern.MatchString(u) {
			u = fmtParamPattern.ReplaceAllString(u, "fmt="+fmt)
		} else {
			u += "&fmt=" + fmt
		}
		if segs, err := c.fetchTimedTextXML(ctx, u); err == nil && len(segs) > 0 {
			return segs, nil
		}
	}
	return c.fetchTimedTextXML(ctx, baseURL)
}

func (c *Client) captionGet(ctx context.Context, u string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", androidUserAgent)
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, classifyNetworkError(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, httpStatusError(resp.StatusCode)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 32<<20))
}

type json3Body struct {
	Events []struct {
		TStartMs    float64 `json:"tStartMs"`
		DDurationMs float64 `json:"dDurationMs"`
		AAppend     any     `json:"aAppend"`
		Segs        []struct {
			UTF8 string `json:"utf8"`
		} `json:"segs"`
	} `json:"events"`
}

func isAppendEvent(v any) bool {
	switch t := v.(type) {
	case bool:
		return t
	case float64:
		return t != 0
	case string:
		return t == "1" || strings.EqualFold(t, "true")
	default:
		return false
	}
}

func (c *Client) fetchJSON3(ctx context.Context, u string) ([]TranscriptSegment, error) {
	data, err := c.captionGet(ctx, u)
	if err != nil {
		return nil, err
	}
	var body json3Body
	if err := json.Unmarshal(data, &body); err != nil {
		return nil, err
	}
	var segments []TranscriptSegment
	for _, ev := range body.Events {
		// aAppend rows are karaoke window advances (often just "\n"), not new cues.
		if isAppendEvent(ev.AAppend) || len(ev.Segs) == 0 {
			continue
		}
		var b strings.Builder
		for _, s := range ev.Segs {
			b.WriteString(s.UTF8)
		}
		text := normalizeCaptionText(b.String())
		if text == "" {
			continue
		}
		segments = append(segments, TranscriptSegment{
			Text: text, Start: ev.TStartMs / 1000, Duration: ev.DDurationMs / 1000,
		})
	}
	return segments, nil
}

func normalizeCaptionText(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.Join(strings.Fields(s), " ")
}
