package youtube

import (
	"strings"
	"testing"
)

func TestParseVideoID(t *testing.T) {
	valid := map[string]string{
		"dQw4w9WgXcQ": "dQw4w9WgXcQ",
		"https://www.youtube.com/watch?v=dQw4w9WgXcQ":        "dQw4w9WgXcQ",
		"https://youtube.com/watch?v=dQw4w9WgXcQ&t=42s":      "dQw4w9WgXcQ",
		"https://youtu.be/dQw4w9WgXcQ":                       "dQw4w9WgXcQ",
		"https://youtu.be/dQw4w9WgXcQ?si=abc":                "dQw4w9WgXcQ",
		"https://www.youtube.com/shorts/dQw4w9WgXcQ":         "dQw4w9WgXcQ",
		"https://www.youtube.com/embed/dQw4w9WgXcQ":          "dQw4w9WgXcQ",
		"https://www.youtube.com/live/dQw4w9WgXcQ":           "dQw4w9WgXcQ",
		"https://m.youtube.com/watch?v=dQw4w9WgXcQ":          "dQw4w9WgXcQ",
		"https://music.youtube.com/watch?v=dQw4w9WgXcQ":      "dQw4w9WgXcQ",
		"youtube.com/watch?v=dQw4w9WgXcQ":                    "dQw4w9WgXcQ",
		"  https://www.youtube.com/watch?v=dQw4w9WgXcQ  ":    "dQw4w9WgXcQ",
		"https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ": "dQw4w9WgXcQ",
	}
	for input, want := range valid {
		got, err := ParseVideoID(input)
		if err != nil {
			t.Errorf("ParseVideoID(%q) unexpected error: %v", input, err)
			continue
		}
		if got != want {
			t.Errorf("ParseVideoID(%q) = %q, want %q", input, got, want)
		}
	}

	invalid := []string{
		"", "short", "https://vimeo.com/12345", "https://example.com/watch?v=dQw4w9WgXcQ",
		"https://www.youtube.com/", "https://www.youtube.com/watch", "not a url at all",
		"dQw4w9WgXc",   // 10 chars
		"dQw4w9WgXcQQ", // 12 chars
	}
	for _, input := range invalid {
		if _, err := ParseVideoID(input); err == nil {
			t.Errorf("ParseVideoID(%q) expected error, got nil", input)
		} else {
			var ee *ExtractError
			if !asExtractError(err, &ee) || ee.Code != "INVALID_VIDEO" {
				t.Errorf("ParseVideoID(%q) expected INVALID_VIDEO, got %v", input, err)
			}
		}
	}
}

func asExtractError(err error, target **ExtractError) bool {
	ee, ok := err.(*ExtractError)
	if ok {
		*target = ee
	}
	return ok
}

func TestPickCaptionTrack(t *testing.T) {
	tracks := []CaptionTrack{
		{LanguageCode: "es", Name: "Spanish", IsAutoGenerated: false},
		{LanguageCode: "en", Name: "English (auto-generated)", IsAutoGenerated: true},
		{LanguageCode: "en-GB", Name: "English (UK)", IsAutoGenerated: false},
	}

	got, err := pickCaptionTrack(tracks, "")
	if err != nil || got.LanguageCode != "es" {
		t.Errorf("default pick = %v, %v; want es manual", got, err)
	}

	got, err = pickCaptionTrack(tracks, "en")
	if err != nil || got.LanguageCode != "en" || !got.IsAutoGenerated {
		t.Errorf("en pick = %v, %v; want en ASR (no manual en exists)", got, err)
	}

	got, err = pickCaptionTrack([]CaptionTrack{tracks[2]}, "en")
	if err != nil || got.LanguageCode != "en-GB" {
		t.Errorf("prefix pick = %v, %v; want en-GB", got, err)
	}

	_, err = pickCaptionTrack(tracks, "fr")
	var ee *ExtractError
	if !asExtractError(err, &ee) || ee.Code != "LANGUAGE_NOT_AVAILABLE" {
		t.Errorf("fr pick expected LANGUAGE_NOT_AVAILABLE, got %v", err)
	}
	if !strings.Contains(ee.Message, "es") {
		t.Errorf("error should list available languages, got %q", ee.Message)
	}

	_, err = pickCaptionTrack(nil, "en")
	if !asExtractError(err, &ee) || ee.Code != "NO_CAPTIONS" {
		t.Errorf("empty tracks expected NO_CAPTIONS, got %v", err)
	}
}

func TestParseChapters(t *testing.T) {
	description := "Intro text here\n0:00 Intro\n1:30 Getting Started\n12:45 Deep Dive\n1:02:03 Wrap up\nSome other line"
	chapters := ParseChapters(description, 4000)
	if len(chapters) != 4 {
		t.Fatalf("expected 4 chapters, got %d: %+v", len(chapters), chapters)
	}
	if chapters[0].Title != "Intro" || chapters[0].StartSeconds != 0 {
		t.Errorf("chapter 0 = %+v", chapters[0])
	}
	if chapters[2].StartSeconds != 765 || chapters[2].Timestamp != "12:45" {
		t.Errorf("chapter 2 = %+v", chapters[2])
	}
	if chapters[3].StartSeconds != 3723 || chapters[3].Timestamp != "1:02:03" {
		t.Errorf("chapter 3 = %+v", chapters[3])
	}

	// No 0:00 start -> not chapters.
	if got := ParseChapters("1:00 One\n2:00 Two", 300); got != nil {
		t.Errorf("expected nil without 0:00 start, got %+v", got)
	}
	// Non-ascending -> not chapters.
	if got := ParseChapters("0:00 A\n5:00 B\n3:00 C", 600); got != nil {
		t.Errorf("expected nil for non-ascending, got %+v", got)
	}
	// Single timestamp -> not chapters.
	if got := ParseChapters("0:00 Only", 600); got != nil {
		t.Errorf("expected nil for single chapter, got %+v", got)
	}
	// Timestamp beyond duration is skipped.
	got := ParseChapters("0:00 A\n2:00 B\n59:00 Beyond", 300)
	if len(got) != 2 {
		t.Errorf("expected out-of-range timestamp to be dropped, got %+v", got)
	}
}

func TestNormalizeCaptionText(t *testing.T) {
	if got := normalizeCaptionText("hello\nworld  again "); got != "hello world again" {
		t.Errorf("normalizeCaptionText = %q", got)
	}
}

func TestClassifyPlayabilityFailure(t *testing.T) {
	cases := map[string]string{
		"ANDROID: LOGIN_REQUIRED (Sign in to confirm your age)": "AUTH_REQUIRED",
		"ANDROID: ERROR (This video is private)":                "PRIVATE_VIDEO",
		"ANDROID: ERROR (Video unavailable)":                    "VIDEO_UNAVAILABLE",
		"ANDROID: RATE_LIMITED: YouTube rate-limited":           "RATE_LIMITED",
	}
	for attempt, wantCode := range cases {
		err := classifyPlayabilityFailure("x", []string{attempt})
		if err.Code != wantCode {
			t.Errorf("classify(%q) = %s, want %s", attempt, err.Code, wantCode)
		}
	}
}
