package youtube

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// TranscriptClip returns only segments overlapping [start, end] seconds.
func (c *Client) TranscriptClip(ctx context.Context, input, lang string, start, end float64) (*Transcript, error) {
	if end > 0 && end <= start {
		return nil, &ExtractError{Code: "INVALID_RANGE",
			Message: "endSeconds must be greater than startSeconds"}
	}
	tr, err := c.Transcript(ctx, input, lang)
	if err != nil {
		return nil, err
	}
	var clipped []TranscriptSegment
	for _, s := range tr.Segments {
		segEnd := s.End
		if segEnd <= start {
			continue
		}
		if end > 0 && s.Start >= end {
			continue
		}
		clipped = append(clipped, s)
	}
	if len(clipped) == 0 {
		return nil, &ExtractError{Code: "EMPTY_CLIP",
			Message: fmt.Sprintf("No transcript segments overlap the range %s–%s",
				FormatTimestamp(start), FormatTimestamp(end)),
			Details: map[string]any{"start": start, "end": end}}
	}
	track := &CaptionTrack{LanguageCode: tr.LanguageCode, Name: tr.LanguageName, IsAutoGenerated: tr.IsAutoGenerated}
	// Clipped rows are already presentation segments; don't merge again.
	out := buildTranscript(tr.VideoID, track, clipped, false, tr.TranslatedFrom)
	out.Merged = tr.Merged
	return out, nil
}

// TranscriptHit is one search match with optional surrounding context.
type TranscriptHit struct {
	Segment TranscriptSegment `json:"segment"`
	Index   int               `json:"index"`
	Context []string          `json:"context,omitempty"`
}

// SearchTranscript finds segments containing query (case-insensitive).
func (c *Client) SearchTranscript(ctx context.Context, input, lang, query string, contextWindow int) (map[string]any, error) {
	query = strings.TrimSpace(query)
	if query == "" {
		return nil, &ExtractError{Code: "USAGE", Message: "search query must not be empty"}
	}
	tr, err := c.Transcript(ctx, input, lang)
	if err != nil {
		return nil, err
	}
	if contextWindow < 0 {
		contextWindow = 0
	}
	if contextWindow > 5 {
		contextWindow = 5
	}
	q := strings.ToLower(query)
	var hits []TranscriptHit
	for i, s := range tr.Segments {
		if !strings.Contains(strings.ToLower(s.Text), q) {
			continue
		}
		hit := TranscriptHit{Segment: s, Index: i}
		from := i - contextWindow
		if from < 0 {
			from = 0
		}
		to := i + contextWindow + 1
		if to > len(tr.Lines) {
			to = len(tr.Lines)
		}
		hit.Context = append([]string{}, tr.Lines[from:to]...)
		hits = append(hits, hit)
	}
	return map[string]any{
		"videoId": tr.VideoID, "query": query, "matchCount": len(hits), "hits": hits,
	}, nil
}

// ExportSubtitles returns captions in the requested format (srt|vtt|ass|json|text).
func (c *Client) ExportSubtitles(ctx context.Context, input, lang, format, outPath string) (map[string]any, error) {
	format = strings.ToLower(strings.TrimSpace(format))
	if format == "" {
		format = "srt"
	}
	tr, err := c.Transcript(ctx, input, lang)
	if err != nil {
		return nil, err
	}
	var body string
	switch format {
	case "srt":
		body = toSRT(tr.Segments)
	case "vtt":
		body = toVTT(tr.Segments)
	case "ass":
		body = toASS(tr.Segments)
	case "json":
		raw, _ := json.MarshalIndent(tr, "", "  ")
		body = string(raw)
	case "text":
		body = strings.Join(tr.Lines, "\n")
	default:
		return nil, &ExtractError{Code: "INVALID_FORMAT",
			Message: fmt.Sprintf("Unsupported subtitle format %q; use srt, vtt, ass, json, or text", format)}
	}
	result := map[string]any{
		"videoId": tr.VideoID, "format": format, "languageCode": tr.LanguageCode,
		"segmentCount": tr.SegmentCount, "content": body,
	}
	if outPath != "" {
		if err := os.WriteFile(outPath, []byte(body), 0o644); err != nil {
			return nil, &ExtractError{Code: "WRITE_ERROR", Message: "Could not write subtitle file: " + err.Error()}
		}
		result["path"] = outPath
	}
	return result, nil
}

func srtTime(seconds float64) string {
	if seconds < 0 {
		seconds = 0
	}
	totalMs := int(seconds*1000 + 0.5)
	h := totalMs / 3_600_000
	m := (totalMs % 3_600_000) / 60_000
	s := (totalMs % 60_000) / 1000
	ms := totalMs % 1000
	return fmt.Sprintf("%02d:%02d:%02d,%03d", h, m, s, ms)
}

func vttTime(seconds float64) string {
	t := srtTime(seconds)
	return strings.Replace(t, ",", ".", 1)
}

func toSRT(segments []TranscriptSegment) string {
	var b strings.Builder
	for i, s := range segments {
		fmt.Fprintf(&b, "%d\n%s --> %s\n%s\n\n", i+1, srtTime(s.Start), srtTime(s.End), s.Text)
	}
	return b.String()
}

func toVTT(segments []TranscriptSegment) string {
	var b strings.Builder
	b.WriteString("WEBVTT\n\n")
	for _, s := range segments {
		fmt.Fprintf(&b, "%s --> %s\n%s\n\n", vttTime(s.Start), vttTime(s.End), s.Text)
	}
	return b.String()
}

func toASS(segments []TranscriptSegment) string {
	var b strings.Builder
	b.WriteString("[Script Info]\nTitle: YouTube Client export\nScriptType: v4.00+\n\n")
	b.WriteString("[V4+ Styles]\n")
	b.WriteString("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
	b.WriteString("Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1\n\n")
	b.WriteString("[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")
	for _, s := range segments {
		fmt.Fprintf(&b, "Dialogue: 0,%s,%s,Default,,0,0,0,,%s\n", assTime(s.Start), assTime(s.End), s.Text)
	}
	return b.String()
}

func assTime(seconds float64) string {
	if seconds < 0 {
		seconds = 0
	}
	totalCs := int(seconds*100 + 0.5)
	h := totalCs / 360000
	m := (totalCs % 360000) / 6000
	s := (totalCs % 6000) / 100
	cs := totalCs % 100
	return fmt.Sprintf("%d:%02d:%02d.%02d", h, m, s, cs)
}
